### ISSUE TITLE
saveFlyData errors on second (and subsequent) use

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#113]
example:

```
In [1]: QXcbConnection: XCB error: 145 (Unknown), sequence: 165, resource id: 0, major code: 139 (Unknown), minor code: 20                                                          
In [1]: RE(usaxs_flyscan.plan())                                                                                                                                                    
HDF5 config: usaxs_support/saveFlyData.xml
HDF5 output: /share1/USAXS_data/test/sfs.h5
5.00s - flying   ar = 8.8856565  ay = 0.00677  dy = 13.14928  channel = 7999  elapsed time = 93.83
10.01s - flying   ar = 8.8847415  ay = 0.00269  dy = 13.13219  channel = 16  elapsed time = 2.80
15.02s - flying   ar = 8.8831987  ay = -0.00268  dy = 13.10956  channel = 47  elapsed time = 7.80
20.02s - flying   ar = 8.8786627  ay = -0.02097  dy = 13.03266  channel = 137  elapsed time = 12.80
25.02s - flying   ar = 8.8679136  ay = -0.06237  dy = 12.85930  channel = 318  elapsed time = 17.80
30.02s - flying   ar = 8.8494464  ay = -0.13275  dy = 12.56342  channel = 583  elapsed time = 22.82
35.03s - flying   ar = 8.8218077  ay = -0.23772  dy = 12.12207  channel = 917  elapsed time = 27.80
40.04s - flying   ar = 8.7840525  ay = -0.38138  dy = 11.52295  channel = 1313  elapsed time = 32.83
45.04s - flying   ar = 8.7350702  ay = -0.56659  dy = 10.73896  channel = 1754  elapsed time = 37.83
50.04s - flying   ar = 8.6736892  ay = -0.80027  dy = 9.77077  channel = 2233  elapsed time = 42.83
55.04s - flying   ar = 8.5985595  ay = -1.07546  dy = 8.59818  channel = 2744  elapsed time = 47.83
60.05s - flying   ar = 8.5111962  ay = -1.40850  dy = 7.20240  channel = 3281  elapsed time = 52.83
65.05s - flying   ar = 8.4079895  ay = -1.79508  dy = 5.56406  channel = 3840  elapsed time = 57.83
70.06s - flying   ar = 8.2879785  ay = -2.24594  dy = 3.69948  channel = 4420  elapsed time = 62.85
75.07s - flying   ar = 8.1531295  ay = -2.74459  dy = 1.56801  channel = 5014  elapsed time = 67.85
80.07s - flying   ar = 8.0013107  ay = -3.31433  dy = -0.81364  channel = 5621  elapsed time = 72.85
85.08s - flying   ar = 7.8329392  ay = -3.95893  dy = -3.54405  channel = 6241  elapsed time = 77.87
90.08s - flying   ar = 7.6452873  ay = -4.65866  dy = -6.44704  channel = 6869  elapsed time = 82.87
95.09s - flying   ar = 7.4431003  ay = -5.43383  dy = -9.72857  channel = 7509  elapsed time = 87.88
100.09s - flying   ar = 7.2361650  ay = -6.15578  dy = -12.79679  channel = 7999  elapsed time = 92.88
101.26s - flying   ar = 7.2361650  ay = -6.15578  dy = -12.79679  channel = 7999  elapsed time = 93.98
Out[1]: ()

HDF5 output complete: /share1/USAXS_data/test/sfs.h5
In [2]: RE(usaxs_flyscan.plan())                                                                                                                                                    
File /share1/USAXS_data/test/sfs.h5 exists.  Will not overwrite.  Using fallback file name /share1/USAXS_data/test/flyscan_20190125_141748.h5
HDF5 config: usaxs_support/saveFlyData.xml
HDF5 output: /share1/USAXS_data/test/flyscan_20190125_141748.h5
Exception in thread Thread-102:
Traceback (most recent call last):
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/32-usaxs_flyscan.py", line 111, in prepare_HDF5_file
    config_file=self.saveFlyData_config)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 220, in __init__
    self._read_configuration()
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 372, in _read_configuration
    Group_Specification(node)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 115, in __init__
    raise RuntimeError(msg)
RuntimeError: Cannot create duplicate HDF5 path names: path=/ name=/ nx_class=file

5.01s - flying   ar = 8.8856565  ay = 0.00677  dy = 13.14928  channel = 7999  elapsed time = 93.98
10.02s - flying   ar = 8.8847443  ay = 0.00287  dy = 13.13196  channel = 15  elapsed time = 2.78
15.02s - flying   ar = 8.8832300  ay = -0.00263  dy = 13.10975  channel = 47  elapsed time = 7.78
20.02s - flying   ar = 8.8786171  ay = -0.02048  dy = 13.03470  channel = 136  elapsed time = 12.78
25.03s - flying   ar = 8.8677379  ay = -0.06202  dy = 12.85994  channel = 317  elapsed time = 17.80
30.03s - flying   ar = 8.8491398  ay = -0.13366  dy = 12.55936  channel = 582  elapsed time = 22.80
35.04s - flying   ar = 8.8219374  ay = -0.23657  dy = 12.12382  channel = 917  elapsed time = 27.80
40.05s - flying   ar = 8.7843811  ay = -0.38151  dy = 11.52489  channel = 1311  elapsed time = 32.82
45.05s - flying   ar = 8.7352895  ay = -0.56390  dy = 10.75026  channel = 1752  elapsed time = 37.82
50.05s - flying   ar = 8.6737163  ay = -0.79802  dy = 9.76218  channel = 2231  elapsed time = 42.82
55.06s - flying   ar = 8.6000003  ay = -1.07351  dy = 8.60177  channel = 2744  elapsed time = 47.83
60.07s - flying   ar = 8.5096838  ay = -1.40620  dy = 7.17579  channel = 3281  elapsed time = 52.83
65.08s - flying   ar = 8.4062451  ay = -1.80214  dy = 5.56371  channel = 3842  elapsed time = 57.85
70.09s - flying   ar = 8.2891683  ay = -2.23835  dy = 3.69659  channel = 4419  elapsed time = 62.85
75.10s - flying   ar = 8.1534366  ay = -2.75178  dy = 1.54317  channel = 5015  elapsed time = 67.87
80.10s - flying   ar = 8.0014709  ay = -3.32234  dy = -0.81717  channel = 5622  elapsed time = 72.87
85.11s - flying   ar = 7.8318364  ay = -3.95907  dy = -3.52605  channel = 6240  elapsed time = 77.87
90.11s - flying   ar = 7.6477210  ay = -4.64384  dy = -6.45880  channel = 6869  elapsed time = 82.87
95.11s - flying   ar = 7.4409929  ay = -5.42571  dy = -9.71887  channel = 7506  elapsed time = 87.87
100.11s - flying   ar = 7.2361650  ay = -6.15578  dy = -12.79679  channel = 7999  elapsed time = 92.89
100.91s - flying   ar = 7.2361650  ay = -6.15578  dy = -12.79679  channel = 7999  elapsed time = 93.65
Exception in thread Thread-109:
Traceback (most recent call last):
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/32-usaxs_flyscan.py", line 117, in finish_HDF5_file
    raise RuntimeError("Must first call prepare_HDF5_file()")
RuntimeError: Must first call prepare_HDF5_file()

```

**Comment by prjemian** [comment]
Aha!  It's the module-level variables which must be re-initialized:

```
field_registry = {}    # key: node/@label,        value: Field_Specification object
group_registry = {}    # key: HDF5 absolute path, value: Group_Specification object
link_registry = {}     # key: node/@label,        value: Link_Specification object
pv_registry = {}       # key: node/@label,        value: PV_Specification object
```

time to refactor

**Comment by prjemian** [comment]
Easy fix for now.  Here is example with the fix:

```
In [1]: RE(usaxs_flyscan.plan())                                                                                                                                                    
File /share1/USAXS_data/test/sfs.h5 exists.  Will not overwrite.  Using fallback file name /share1/USAXS_data/test/flyscan_20190125_142934.h5
HDF5 config: usaxs_support/saveFlyData.xml
HDF5 output: /share1/USAXS_data/test/flyscan_20190125_142934.h5
5.01s - flying   ar = 8.8856565  ay = 0.00677  dy = 13.14928  channel = 7999  elapsed time = 94.08
10.02s - flying   ar = 8.8846805  ay = 0.00273  dy = 13.13193  channel = 16  elapsed time = 2.82
15.02s - flying   ar = 8.8832058  ay = -0.00265  dy = 13.10928  channel = 47  elapsed time = 7.82
20.03s - flying   ar = 8.8786597  ay = -0.02115  dy = 13.03330  channel = 138  elapsed time = 12.82
25.04s - flying   ar = 8.8676225  ay = -0.06233  dy = 12.85980  channel = 320  elapsed time = 17.83
30.04s - flying   ar = 8.8492728  ay = -0.13275  dy = 12.56157  channel = 584  elapsed time = 22.83
35.05s - flying   ar = 8.8212297  ay = -0.23684  dy = 12.11795  channel = 918  elapsed time = 27.82
40.05s - flying   ar = 8.7830438  ay = -0.38069  dy = 11.51080  channel = 1314  elapsed time = 32.85
45.06s - flying   ar = 8.7344886  ay = -0.56783  dy = 10.73826  channel = 1755  elapsed time = 37.85
50.06s - flying   ar = 8.6734181  ay = -0.79768  dy = 9.76862  channel = 2235  elapsed time = 42.85
55.07s - flying   ar = 8.5977487  ay = -1.07747  dy = 8.57171  channel = 2748  elapsed time = 47.87
60.08s - flying   ar = 8.5098946  ay = -1.40828  dy = 7.16126  channel = 3285  elapsed time = 52.87
65.08s - flying   ar = 8.4079454  ay = -1.79657  dy = 5.53431  channel = 3844  elapsed time = 57.87
70.08s - flying   ar = 8.2896743  ay = -2.24424  dy = 3.68341  channel = 4422  elapsed time = 62.88
75.09s - flying   ar = 8.1542716  ay = -2.74427  dy = 1.54453  channel = 5017  elapsed time = 67.88
80.09s - flying   ar = 8.0023039  ay = -3.32186  dy = -0.86568  channel = 5624  elapsed time = 72.88
85.09s - flying   ar = 7.8340412  ay = -3.94931  dy = -3.50075  channel = 6243  elapsed time = 77.88
90.10s - flying   ar = 7.6452088  ay = -4.65292  dy = -6.45323  channel = 6872  elapsed time = 82.88
95.10s - flying   ar = 7.4401751  ay = -5.42753  dy = -9.76382  channel = 7511  elapsed time = 87.90
100.11s - flying   ar = 7.2361650  ay = -6.15578  dy = -12.79679  channel = 7999  elapsed time = 92.90
101.21s - flying   ar = 7.2361650  ay = -6.15578  dy = -12.79679  channel = 7999  elapsed time = 93.95
Out[1]: ()

HDF5 output complete: /share1/USAXS_data/test/flyscan_20190125_142934.h5
In [2]: RE(usaxs_flyscan.plan())                                                                                                                                                    
File /share1/USAXS_data/test/sfs.h5 exists.  Will not overwrite.  Using fallback file name /share1/USAXS_data/test/flyscan_20190125_143124.h5
HDF5 config: usaxs_support/saveFlyData.xml
HDF5 output: /share1/USAXS_data/test/flyscan_20190125_143124.h5
5.01s - flying   ar = 8.8856565  ay = 0.00677  dy = 13.14928  channel = 7999  elapsed time = 93.95
10.01s - flying   ar = 8.8847509  ay = 0.00287  dy = 13.13283  channel = 15  elapsed time = 2.78
15.02s - flying   ar = 8.8832282  ay = -0.00268  dy = 13.10970  channel = 47  elapsed time = 7.80
20.02s - flying   ar = 8.8786860  ay = -0.02057  dy = 13.03273  channel = 137  elapsed time = 12.80
25.02s - flying   ar = 8.8679597  ay = -0.06275  dy = 12.85807  channel = 317  elapsed time = 17.80
30.03s - flying   ar = 8.8492728  ay = -0.13336  dy = 12.56386  channel = 580  elapsed time = 22.80
35.03s - flying   ar = 8.8215806  ay = -0.23777  dy = 12.11772  channel = 916  elapsed time = 27.80
40.03s - flying   ar = 8.7841910  ay = -0.37967  dy = 11.51177  channel = 1309  elapsed time = 32.80
45.04s - flying   ar = 8.7352128  ay = -0.56381  dy = 10.73421  channel = 1751  elapsed time = 37.82
50.04s - flying   ar = 8.6734995  ay = -0.79700  dy = 9.76368  channel = 2230  elapsed time = 42.82
55.05s - flying   ar = 8.5987660  ay = -1.07870  dy = 8.57428  channel = 2741  elapsed time = 47.82
60.05s - flying   ar = 8.5117884  ay = -1.40520  dy = 7.19968  channel = 3278  elapsed time = 52.82
65.06s - flying   ar = 8.4090695  ay = -1.79300  dy = 5.53781  channel = 3839  elapsed time = 57.83
70.07s - flying   ar = 8.2899019  ay = -2.24613  dy = 3.68631  channel = 4416  elapsed time = 62.83
75.07s - flying   ar = 8.1546140  ay = -2.74834  dy = 1.54769  channel = 5011  elapsed time = 67.85
80.08s - flying   ar = 8.0032645  ay = -3.31313  dy = -0.85304  channel = 5618  elapsed time = 72.85
85.09s - flying   ar = 7.8340412  ay = -3.95639  dy = -3.52042  channel = 6237  elapsed time = 77.87
90.09s - flying   ar = 7.6485057  ay = -4.65189  dy = -6.46747  channel = 6867  elapsed time = 82.87
95.10s - flying   ar = 7.4415952  ay = -5.42296  dy = -9.71411  channel = 7505  elapsed time = 87.87
100.10s - flying   ar = 7.2361650  ay = -6.15578  dy = -12.79679  channel = 7999  elapsed time = 92.87
100.76s - flying   ar = 7.2361650  ay = -6.15578  dy = -12.79679  channel = 7999  elapsed time = 93.50
Out[2]: ()

HDF5 output complete: /share1/USAXS_data/test/flyscan_20190125_143124.h5
```
