### ISSUE TITLE
preUSAXStune() failed to open mono shutter

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#162]
* initially failed to open the mono shutter so suspender tripped
* opened shutter in GUI
* this error cascade appeared (some float vs. tuple error with the pf4 was the first problem)

```
In [5]: RE(preUSAXStune())                                                                                                                                               
At least one suspender has tripped. The plan will begin when all suspenders are ready. Justification:
    1. Signal usaxs_CheckBeamStandard is low

Suspending... To get to the prompt, hit Ctrl-C twice to pause.
Suspender SuspendBoolLow(EpicsSignal(read_pv='9idcLAX:blCalc:userCalc1', name='usaxs_CheckBeamStandard', value=0.0, timestamp=1554309163.397676, tolerance=1e-05, auto_monitor=False, string=False, write_pv='9idcLAX:blCalc:userCalc1', limits=False, put_complete=False), sleep=0, pre_plan=None, post_plan=None,tripped_message=) reports a return to nominal conditions. Will sleep for 0 seconds and then release suspension at 2019-04-03 11:33:01.
Suspender SuspendBoolLow(EpicsSignal(read_pv='9idcLAX:blCalc:userCalc1', name='usaxs_CheckBeamStandard', value=1.0, timestamp=1554309221.298626, tolerance=1e-05, auto_monitor=False, string=False, write_pv='9idcLAX:blCalc:userCalc1', limits=False, put_complete=False), sleep=0, pre_plan=None, post_plan=None,tripped_message=) reports a return to nominal conditions. Will sleep for 0 seconds and then release suspension at 2019-04-03 11:33:41.
set_and_wait('pf4_AlTi_fPosA', 0.0) failed
Traceback (most recent call last):
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/ophyd/signal.py", line 230, in set_thread
    rtol=self.rtolerance)
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/ophyd/utils/epics_pvs.py", line 257, in set_and_wait
    rtol):
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/ophyd/utils/epics_pvs.py", line 274, in _compare_maybe_enum
    a = enums[a]
TypeError: tuple indices must be integers or slices, not float
set_and_wait('pf4_AlTi_fPosB', 0.0) failed
Traceback (most recent call last):
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/ophyd/signal.py", line 230, in set_thread
    rtol=self.rtolerance)
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/ophyd/utils/epics_pvs.py", line 257, in set_and_wait
    rtol):
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/ophyd/utils/epics_pvs.py", line 274, in _compare_maybe_enum
    a = enums[a]
TypeError: tuple indices must be integers or slices, not float
---------------------------------------------------------------------------
FailedStatus                              Traceback (most recent call last)
<ipython-input-5-f92c9110a1e3> in <module>
----> 1 RE(preUSAXStune())

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    742                     # it (unless it is a canceled error)
    743                     if exc is not None:
--> 744                         raise exc
    745 
    746             if self._interrupted:

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1251             self.log.error("Run aborted")
   1252             self.log.error("%r", err)
-> 1253             raise err
   1254         finally:
   1255             # Some done_callbacks may still be alive in other threads.

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/run_engine.py in _run(self)
   1115                         try:
   1116                             msg = self._plan_stack[-1].throw(
-> 1117                                 self._exception or resp)
   1118                         except Exception as e:
   1119                             # The current plan did not handle it,

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1147         return (yield from plan)
   1148     else:
-> 1149         return (yield from plan_mutator(plan, insert_baseline))
   1150 
   1151 

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791 
    792 

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849 
    850 

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py in preUSAXStune(md)
     27     yield from IfRequestedStopBeforeNextScan()         # stop if user chose to do so.
     28 
---> 29     yield from mode_USAXS()
     30 
     31     yield from bps.mv(

/home/beams11/USAXS/.ipython/profile_bluesky/startup/43-procedures.py in mode_USAXS()
    126         # print("Change TV input selector to show image in hutch")
    127         # print("Turn off BLUE switch on CCD controller")
--> 128         yield from insertScanFilters()
    129         yield from bps.mv(ccd_shutter, "close")
    130 

/home/beams11/USAXS/.ipython/profile_bluesky/startup/43-procedures.py in insertScanFilters()
     43     yield from _insertFilters_(
     44         terms.USAXS.scan_filters.Al.value,    # Bank A: Al
---> 45         terms.USAXS.scan_filters.Ti.value,    # Bank B: Ti
     46     )
     47 

/home/beams11/USAXS/.ipython/profile_bluesky/startup/43-procedures.py in _insertFilters_(a, b)
     19 def _insertFilters_(a, b):
     20     """plan: insert the EPICS-specified filters"""
---> 21     yield from bps.mv(pf4_AlTi.fPosA, a, pf4_AlTi.fPosB, b)
     22     yield from bps.sleep(0.5)       # allow all blades to re-position
     23 

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/plan_stubs.py in mv(*args)
    245         ret = yield Msg('set', obj, val, group=group)
    246         status_objects.append(ret)
--> 247     yield Msg('wait', None, group=group)
    248     return tuple(status_objects)
    249 

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/APSshare/anaconda3/BlueSky/lib/python3.6/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

FailedStatus: Status(obj=EpicsSignal(read_pv='9idcRIO:pf4:fPosA', name='pf4_AlTi_fPosA', parent='pf4_AlTi', value=0, timestamp=1554309221.325716, auto_monitor=False, string=False, write_pv='9idcRIO:pf4:fPosA', limits=False, put_complete=False), done=True, success=False)
```

**Comment by prjemian** [comment]
Consider this [suggestion](https://github.com/APS-USAXS/ipython-usaxs/issues/169#issuecomment-482180697) how to resolve the original issue here.  (Add calls to `bps.install_suspender()` and `bps.remove_suspender()` as desired, deftly avoiding suspension of the code that needs to run when the shutter is closed.)

```
... some other plan activities
yield from bps.mv(mono_shutter, "open")
yield from bps.install_suspender(watch_the_mono_shutter)
... plan activities that should pause if the mono shutter closes
yield from bps.remove_suspender(watch_the_mono_shutter)
yield from bps.mv(mono_shutter, "close")
... some other plan activities
```

**Comment by prjemian** [comment]
Changeset 3c2d022 is related to this issue.

**Comment by prjemian** [comment]
Closing this issue since #170 will be used to follow adoption of the revised algorithm.
