### ISSUE TITLE
KeyError: 'set_state' then AttributeError: set_state during FlyScan

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#173]
```
125.12s - flying   ar = 7.3522883  ay = -5.45836  dy = -11.05857  channel = 7821  elapsed time = 119.87
129.16s - flying   ar = 7.2309840  ay = -5.85952  dy = -12.80124  channel = 7999  elapsed time = 123.87
Exception in thread Thread-908:
Traceback (most recent call last):
  File "/local/Apps/BlueSky/lib/python3.7/site-packages/ophyd/device.py", line 984, in __getattr__
    cpt = self._sig_attrs[name]
KeyError: 'set_state'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/local/Apps/BlueSky/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/local/Apps/BlueSky/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/32-usaxs_flyscan.py", line 78, in progress_reporting
    user_data.set_state("flying: " + msg.split()[0])
  File "/local/Apps/BlueSky/lib/python3.7/site-packages/ophyd/device.py", line 987, in __getattr__
    raise AttributeError(name)
AttributeError: set_state

New stream: 'mca'                                                                                                                                                
HDF5 output complete: /share1/USAXS_data/2019-04/04_19_test_usaxs/Blank_0002.h5
/local/Apps/BlueSky/lib/python3.7/site-packages/bluesky/run_engine.py:485: RuntimeWarning: coroutine 'Event.wait' was never awaited
```

**Comment by prjemian** [comment]
related, in part, to #172

**Comment by prjemian** [comment]
Are we trying to restore (unstage or other) a read-only value?

**Comment by prjemian** [comment]
This was a cosmetic error, only affecting reports to the console and to the EPICS USAXS scanning status PV
