### ISSUE TITLE
reporting thread crashes after larger number of flyscans

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#181]
After about 10 scans we start receiving e-mails that flyscans have less than expected number of PSO pulses. Looks like some variable used for checking if we have appropriate number of mca channels is not reset as needed. 
At the same time, reporting thread has crashed, see below. The time of this crash is associated with number of channels reported via e-mail as missing. More channels = earlier crash of this thread. Note: Data are OK, no channels are missing. 

```
65.08s - flying   ar = 8.4953960  ay = -1.38742  dy = 6.76980  channel = 4032  elapsed time = 59.83
70.09s - flying   ar = 8.3663468  ay = -1.84553  dy = 4.74838  channel = 4670  elapsed time = 64.83
Exception in thread Thread-8699:
Traceback (most recent call last):
  File "/local/Apps/BlueSky/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/local/Apps/BlueSky/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/32-usaxs_flyscan.py", line 70, in progress_reporting
    msg = _report_(t - self.t0)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/32-usaxs_flyscan.py", line 45, in _report_
    if elapsed > t:     # looking at previous fly scan
TypeError: '>' not supported between instances of 'NoneType' and 'float'

HDF5 output complete: /share1/USAXS_data/2019-04/04_19_test_usaxs/NaOH_11_0035.h5             
```

**Comment by prjemian** [comment]
Email says

```
subject: !!! bad number of PSO pulses !!!
message: WARNING: Flyscan finished with 2044 less points
```

**Comment by prjemian** [comment]
use `.get()` instead of `.value` when immediate value of signal is needed
