### ISSUE TITLE
KeyError from measure_USAXS_Transmission

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#196]
While working on #143, this exception was raised:

```
In [2]: RE(measure_USAXS_Transmission(md=dict(purpose="issue 143")))                                                                                                   
Transient Scan ID: 1     Time: 2019-05-02 15:55:55                                                                                                                     
Persistent Unique Scan ID: 'e9e5f7f9-f258-49a0-bcb0-bb8f6fb13cbe'                                                                                                      
New stream: 'baseline'
Start-of-run baseline readings:
+--------------------------------+--------------------------------+
|                 guard_slit_bot | -0.5                           |
|                 guard_slit_inb | -0.5311999999999983            |
|                guard_slit_outb | 0.5311999999999557             |
|                 guard_slit_top | 0.5                            |
|                   guard_slit_x | -0.015000000000000568          |
|                   guard_slit_y | 14.546484765624996             |
|              usaxs_slit_h_size | 0.7000007999999944             |
|                   usaxs_slit_x | 8.000000001118224e-06          |
|              usaxs_slit_v_size | 0.7000759999999993             |
|                   usaxs_slit_y | 0.24993599999999994            |
+--------------------------------+--------------------------------+
New stream: 'primary'                                                                                                                                                  
+-----------+------------+------------+------------+------------+------------+------------+------------+
|   seq_num |       time |    seconds |   I0_USAXS |  I00_USAXS |   PD_USAXS |   TR diode |       I000 |
+-----------+------------+------------+------------+------------+------------+------------+------------+
|         1 | 15:55:58.7 |   30000000 |       3725 |      94175 |     659647 |          1 |          0 |
+-----------+------------+------------+------------+------------+------------+------------+------------+
generator measure_USAXS_Transmission ['e9e5f7f9'] (scan num: 1)
End-of-run baseline readings:
+--------------------------------+--------------------------------+
|                 guard_slit_bot | -0.5                           |
|                 guard_slit_inb | -0.5311999999999983            |
|                guard_slit_outb | 0.5311999999999557             |
|                 guard_slit_top | 0.5                            |
|                   guard_slit_x | -0.015000000000000568          |
|                   guard_slit_y | 14.546484765624996             |
|              usaxs_slit_h_size | 0.7000007999999944             |
|                   usaxs_slit_x | 8.000000001118224e-06          |
|              usaxs_slit_v_size | 0.7000759999999993             |
|                   usaxs_slit_y | 0.24993599999999994            |
+--------------------------------+--------------------------------+



exit status: fail
# descriptor(s): 2
# event(s): 3
[E 15:55:59.252 run_engine:1264] Run aborted
    Traceback (most recent call last):
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1153, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1149, in baseline_wrapper
        return (yield from plan_mutator(plan, insert_baseline))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/43-procedures.py", line 353, in measure_USAXS_Transmission
        yield from bp.count([scaler0], md=md)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plans.py", line 67, in count
        return (yield from inner_count())
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py", line 1011, in dec_inner
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 939, in stage_wrapper
        return (yield from finalize_wrapper(inner(), unstage_devices()))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 500, in finalize_wrapper
        ret = yield from plan
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 937, in inner
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py", line 1011, in dec_inner
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 326, in run_wrapper
        else_plan=close_run)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 562, in contingency_wrapper
        ret = yield from plan
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plans.py", line 65, in inner_count
        num=num, delay=delay))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 1022, in repeat
        return (yield from repeated_plan())
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 1005, in repeated_plan
        yield from ensure_generator(plan())
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 802, in trigger_and_read
        rewindable))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 680, in rewindable_wrapper
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 798, in inner_trigger_and_read
        yield from save()
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 57, in save
        return (yield Msg('save'))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      [Previous line repeated 2 more times]
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1211, in _run
        new_response = yield from coro(msg)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1720, in _save
        yield from self.emit(DocumentNames.event, doc)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/asyncio/coroutines.py", line 120, in coro
        res = func(*args, **kw)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 2324, in emit
        self.dispatcher.process(name, doc)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 2344, in process
        exceptions = self.cb_registry.process(name, name.name, doc)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py", line 334, in process
        func(*args, **kwargs)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py", line 415, in __call__
        return mtd(*args, **kwargs)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/filewriters.py", line 261, in receiver
        xref[key](document)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/filewriters.py", line 375, in event
        v = doc["data"][k]
    KeyError: 'scaler0'
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-2-b34a9a050b29> in <module>
----> 1 RE(measure_USAXS_Transmission(md=dict(purpose="issue 143")))

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    754                     # it (unless it is a canceled error)
    755                     if exc is not None:
--> 756                         raise exc
    757 
    758             if self._interrupted:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1263             self._reason = str(err)
   1264             self.log.exception("Run aborted")
-> 1265             raise err
   1266         finally:
   1267             # Some done_callbacks may still be alive in other threads.

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1151                     else:
   1152                         try:
-> 1153                             msg = self._plan_stack[-1].send(resp)
   1154                         # We have exhausted the top generator
   1155                         except StopIteration:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1147         return (yield from plan)
   1148     else:
-> 1149         return (yield from plan_mutator(plan, insert_baseline))
   1150 
   1151 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791 
    792 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849 
    850 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/home/beams11/USAXS/.ipython/profile_bluesky/startup/43-procedures.py in measure_USAXS_Transmission(md)
    351         )
    352         md["plan_name"] = "measure_USAXS_Transmission"
--> 353         yield from bp.count([scaler0], md=md)
    354         s = scaler0.read()
    355         secs = s["scaler0_time"]["value"]

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plans.py in count(detectors, num, delay, md)
     65                                       num=num, delay=delay))
     66 
---> 67     return (yield from inner_count())
     68 
     69 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1009                 plan = gen_func(*inner_args, **inner_kwargs)
   1010                 plan = wrapper(plan, *args, **kwargs)
-> 1011                 return (yield from plan)
   1012             return dec_inner
   1013         return dec

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in stage_wrapper(plan, devices)
    937         return (yield from plan)
    938 
--> 939     return (yield from finalize_wrapper(inner(), unstage_devices()))
    940 
    941 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for_debug)
    498     cleanup = True
    499     try:
--> 500         ret = yield from plan
    501     except GeneratorExit:
    502         cleanup = False

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in inner()
    935     def inner():
    936         yield from stage_devices()
--> 937         return (yield from plan)
    938 
    939     return (yield from finalize_wrapper(inner(), unstage_devices()))

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1009                 plan = gen_func(*inner_args, **inner_kwargs)
   1010                 plan = wrapper(plan, *args, **kwargs)
-> 1011                 return (yield from plan)
   1012             return dec_inner
   1013         return dec

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in run_wrapper(plan, md)
    324     yield from contingency_wrapper(plan,
    325                                    except_plan=except_plan,
--> 326                                    else_plan=close_run)
    327     return rs_uid
    328 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in contingency_wrapper(plan, except_plan, else_plan, final_plan, pause_for_debug)
    560     cleanup = True
    561     try:
--> 562         ret = yield from plan
    563     except GeneratorExit:
    564         cleanup = False

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plans.py in inner_count()
     63     def inner_count():
     64         return (yield from bps.repeat(partial(bps.trigger_and_read, detectors),
---> 65                                       num=num, delay=delay))
     66 
     67     return (yield from inner_count())

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py in repeat(plan, num, delay)
   1020                     yield Msg('sleep', None, d)
   1021 
-> 1022     return (yield from repeated_plan())

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py in repeated_plan()
   1003             now = time.time()  # Intercept the flow in its earliest moment.
   1004             yield Msg('checkpoint')
-> 1005             yield from ensure_generator(plan())
   1006             try:
   1007                 d = next(delay)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py in trigger_and_read(devices, name)
    800     from .preprocessors import rewindable_wrapper
    801     return (yield from rewindable_wrapper(inner_trigger_and_read(),
--> 802                                           rewindable))
    803 
    804 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in rewindable_wrapper(plan, rewindable)
    678                                             restore_rewindable()))
    679     else:
--> 680         return (yield from plan)
    681 
    682 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py in inner_trigger_and_read()
    796             if reading is not None:
    797                 ret.update(reading)
--> 798         yield from save()
    799         return ret
    800     from .preprocessors import rewindable_wrapper

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py in save()
     55     :func:`bluesky.plan_stubs.create`
     56     """
---> 57     return (yield Msg('save'))
     58 
     59 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1209                         # exceptions (coming in via throw) can be
   1210                         # raised
-> 1211                         new_response = yield from coro(msg)
   1212 
   1213                     # special case `CancelledError` and let the outer

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _save(self, msg)
   1718                    time=ttime.time(), data=data, timestamps=timestamps,
   1719                    seq_num=seq_num, uid=event_uid, filled=filled)
-> 1720         yield from self.emit(DocumentNames.event, doc)
   1721         self.log.debug("Emitted Event with data keys %r (uid=%r)", data.keys(),
   1722                        event_uid)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/asyncio/coroutines.py in coro(*args, **kw)
    118         @functools.wraps(func)
    119         def coro(*args, **kw):
--> 120             res = func(*args, **kw)
    121             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    122                     isinstance(res, CoroWrapper)):

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in emit(self, name, doc)
   2322         "Process blocking callbacks and schedule non-blocking callbacks."
   2323         _validate(doc, schemas[name])
-> 2324         self.dispatcher.process(name, doc)
   2325 
   2326 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in process(self, name, doc)
   2342         doc : dict
   2343         """
-> 2344         exceptions = self.cb_registry.process(name, name.name, doc)
   2345         for exc, traceback in exceptions:
   2346             warn("A %r was raised during the processing of a %s "

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py in process(self, sig, *args, **kwargs)
    332             for cid, func in list(self.callbacks[sig].items()):
    333                 try:
--> 334                     func(*args, **kwargs)
    335                 except ReferenceError:
    336                     self._remove_proxy(func)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py in __call__(self, *args, **kwargs)
    413             mtd = self.func
    414         # invoke the callable and return the result
--> 415         return mtd(*args, **kwargs)
    416 
    417     def __eq__(self, other):

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/filewriters.py in receiver(self, key, document)
    259                 ts = datetime.fromtimestamp(document["time"])
    260             self._datetime = ts
--> 261             xref[key](document)
    262         else:
    263             msg = f"custom_callback encountered: {key} : {document}"

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/filewriters.py in event(self, doc)
    373                     v = doc["time"] - self.time
    374                 else:
--> 375                     v = doc["data"][k]
    376                 self.data[k].append(v)
    377             self.num_primary_data += 1

KeyError: 'scaler0'

In [3]:                                                                                                                                                                ```

**Comment by prjemian** [comment]
should use channel names, not `scaler0`

**Comment by prjemian** [comment]
Fixed over [there](https://github.com/BCDA-APS/apstools/issues/127), fix applied locally.
