### ISSUE TITLE
ValueError at end of tune_mr() part of Flyscan()

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#203]
<details>
<summary>Exception trace:</summary>
<p>

```
(base) usaxs@usaxscontrol .../USAXS_data/2019-05 $ !ipy
ipython --profile=bluesky
Python 3.7.2 (default, Dec 29 2018, 06:19:36)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.2.0 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: bluesky
/home/beams11/USAXS/.ipython/profile_bluesky/startup/00-0-checks.py
BlueSky version: 1.5.2
Ophyd version: 1.3.3
/home/beams11/USAXS/.ipython/profile_bluesky/startup/00-startup.py
Loading metadata history from /home/beams/USAXS/.config/bluesky/bluesky_history.db
/home/beams11/USAXS/.ipython/profile_bluesky/startup/01-databroker.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/02-pyepics.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/09-imports.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/10-devices.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/11-motors.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/19-constants.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/20-detectors.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/21-aps.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/21-filters_shutters.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Session started when APS not operating.
Using simulators for FE_shutter and mono_shutter.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
/home/beams11/USAXS/.ipython/profile_bluesky/startup/21-signals.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/22-amplifiers.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/24-detector_data_file_names.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/24-overrides_hdf5.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/25-alta.py
Timeout connecting with Alta (9idalta:)
/home/beams11/USAXS/.ipython/profile_bluesky/startup/25-blackfly.py
Timeout connecting with PointGrey BlackFly (9idFLY1:)
/home/beams11/USAXS/.ipython/profile_bluesky/startup/25-pilatus.py
Timeout connecting with Pilatus 100k (usaxs_pilatus1:)
Timeout connecting with Pilatus 200kw (usaxs_pilatus2:)
/home/beams11/USAXS/.ipython/profile_bluesky/startup/25-simdetector.py
Timeout connecting with SimDetector (9idcSIM1:)
/home/beams11/USAXS/.ipython/profile_bluesky/startup/28-protection_plc.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/32-usaxs_flyscan.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/41-commands.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/43-procedures.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py
/home/beams11/USAXS/.ipython/profile_bluesky/startup/60-metadata.py
Metadata dictionary:
RE.md['APSTOOLS_VERSION'] = 1.1.3
RE.md['BLUESKY_VERSION'] = 1.5.2
RE.md['EPICS_CA_MAX_ARRAY_BYTES'] = 1280000
RE.md['EPICS_HOST_ARCH'] = linux-x86_64
RE.md['OPHYD_VERSION'] = 1.3.3
RE.md['beamline_id'] = APS USAXS 9-ID-C
RE.md['login_id'] = usaxs@usaxscontrol.xray.aps.anl.gov
RE.md['pid'] = 21432
RE.md['proposal_id'] = testing Bluesky installation
RE.md['scan_id'] = 1
/home/beams11/USAXS/.ipython/profile_bluesky/startup/80-callbacks.py

writing to SPEC file: 20190513-155452.dat
>>>>   Using default SPEC file name   <<<<
file will be created when bluesky ends its next scan
to change SPEC file, use command: newSpecFile('title')

In [1]: newSpecFile("test11")
SPEC file name : 05_13_test11.dat
Current working directory : /share1/USAXS_data/2019-05
file will be created when bluesky ends its next scan

In [2]: RE(Flyscan(60, 160, 0, "blank", md=dict(purpose="issue 143")))
metadata={'purpose': 'issue 143', 'plan_name': 'tune_mr'}
tuning axis:  m_stage_r
Tuning axis m_stage_r, current position is 8.824977
Transient Scan ID: 1     Time: 2019-05-13 15:55:24
Persistent Unique Scan ID: '91d5edf4-413a-4961-af89-94dca8c58db2'
New stream: 'baseline'
Start-of-run baseline readings:
+--------------------------------+--------------------------------+
|                 guard_slit_bot | -0.5                           |
|                 guard_slit_inb | -0.5311999999999983            |
|                guard_slit_outb | 0.5311999999999557             |
|                 guard_slit_top | 0.5                            |
|                   guard_slit_x | -0.015000000000000568          |
|                   guard_slit_y | 14.546484765624996             |
|              usaxs_slit_h_size | 0.7000007999999944             |
|                   usaxs_slit_x | 8.000000001118224e-06          |
|              usaxs_slit_v_size | 0.7000759999999993             |
|                   usaxs_slit_y | 0.24993599999999994            |
+--------------------------------+--------------------------------+
New stream: 'primary'
+-----------+------------+------------+------------+
|   seq_num |       time |  m_stage_r |   I0_USAXS |
+-----------+------------+------------+------------+
|         1 | 15:55:26.0 |  8.8269770 |        133 |
|         2 | 15:55:26.4 |  8.8268440 |        131 |
|         3 | 15:55:26.9 |  8.8267110 |        132 |
|         4 | 15:55:27.3 |  8.8265770 |        133 |
|         5 | 15:55:27.7 |  8.8264440 |        131 |
|         6 | 15:55:28.1 |  8.8263110 |        132 |
|         7 | 15:55:28.5 |  8.8261770 |        132 |
|         8 | 15:55:28.9 |  8.8260440 |        131 |
|         9 | 15:55:29.3 |  8.8259110 |        132 |
|        10 | 15:55:29.7 |  8.8257770 |        131 |
|        11 | 15:55:30.2 |  8.8256440 |        133 |
|        12 | 15:55:30.6 |  8.8255110 |        132 |
|        13 | 15:55:31.0 |  8.8253770 |        132 |
|        14 | 15:55:31.4 |  8.8252440 |        132 |
|        15 | 15:55:31.8 |  8.8251110 |        132 |
|        16 | 15:55:32.2 |  8.8249770 |        132 |
|        17 | 15:55:32.6 |  8.8248440 |        132 |
|        18 | 15:55:33.1 |  8.8247110 |        133 |
|        19 | 15:55:33.4 |  8.8245770 |        131 |
|        20 | 15:55:33.9 |  8.8244440 |        132 |
|        21 | 15:55:34.3 |  8.8243110 |        133 |
|        22 | 15:55:34.7 |  8.8241770 |        132 |
|        23 | 15:55:35.1 |  8.8240440 |        133 |
|        24 | 15:55:35.5 |  8.8239110 |        132 |
|        25 | 15:55:36.0 |  8.8237770 |        132 |
|        26 | 15:55:36.4 |  8.8236440 |        132 |
|        27 | 15:55:36.8 |  8.8235110 |        133 |
|        28 | 15:55:37.2 |  8.8233770 |        133 |
|        29 | 15:55:37.6 |  8.8232440 |        132 |
|        30 | 15:55:38.1 |  8.8231110 |        132 |
|        31 | 15:55:38.5 |  8.8229770 |          4 |
[E 15:55:38.521 run_engine:1264] Run aborted
    Traceback (most recent call last):
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1153, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1149, in baseline_wrapper
        return (yield from plan_mutator(plan, insert_baseline))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapp                                                                         er
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 135, in Flyscan
        yield from tune_usaxs_optics(md=md)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py", line 455, in tune_usaxs_optics
        yield from tune_mr(md=md)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py", line 143, in tune_mr
        yield from _tune_base_(m_stage.r, md=md)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py", line 121, in _tune_base_
        yield from axis.tune(md=md)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py", line 983, in tune
        yield from self.tuner.tune(md=md, **kwargs)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/plans.py", line 634, in tune
        return (yield from _scan(md=_md))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py", line 1011, in dec_inner
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 382, in subs_wrapper
        _unsubscribe()))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 500, in finalize_wrapper
        ret = yield from plan
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 379, in _inner_plan
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/plans.py", line 625, in _scan
        yield from bps.read(results)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 90, in read
        return (yield Msg('read', obj))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      [Previous line repeated 2 more times]
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1211, in _run
        new_response = yield from coro(msg)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/asyncio/coroutines.py", line 120, in coro
        res = func(*args, **kw)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1494, in _read
        data_keys = obj.describe()
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/ophyd/device.py", line 1037, in describe
        res.update(component.describe())
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/ophyd/signal.py", line 218, in describe
        'dtype': data_type(val),
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/ophyd/utils/epics_pvs.py", line 313, in data_type
        'not a valid type (int, float, ndarray, str, list, tuple)')
    ValueError: None not a valid type (int, float, ndarray, str, list, tuple)
+-----------+------------+------------+------------+
generator tune_mr ['91d5edf4'] (scan num: 1)



exit status: fail
# descriptor(s): 2
# event(s): 32
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-2-39748ded1500> in <module>
----> 1 RE(Flyscan(60, 160, 0, "blank", md=dict(purpose="issue 143")))

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    754                     # it (unless it is a canceled error)
    755                     if exc is not None:
--> 756                         raise exc
    757
    758             if self._interrupted:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1263             self._reason = str(err)
   1264             self.log.exception("Run aborted")
-> 1265             raise err
   1266         finally:
   1267             # Some done_callbacks may still be alive in other threads.

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1151                     else:
   1152                         try:
-> 1153                             msg = self._plan_stack[-1].send(resp)
   1154                         # We have exhausted the top generator
   1155                         except StopIteration:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1147         return (yield from plan)
   1148     else:
-> 1149         return (yield from plan_mutator(plan, insert_baseline))
   1150
   1151

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791
    792

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849
    850

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py in Flyscan(pos_X, pos_Y, thickness, scan_title, md)
    133         # tune at previous sample position
    134         # don't overexpose the new sample position
--> 135         yield from tune_usaxs_optics(md=md)
    136
    137     yield from bps.mv(

/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py in tune_usaxs_optics(side, md)
    453         yield from bps.install_suspender(suspend_BeamInHutch)
    454
--> 455     yield from tune_mr(md=md)
    456     yield from tune_m2rp(md=md)
    457     if side:

/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py in tune_mr(md)
    141     md['plan_name'] = "tune_mr"
    142     print(f"metadata={md}")
--> 143     yield from _tune_base_(m_stage.r, md=md)
    144
    145

/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py in _tune_base_(axis, md)
    119         ti_filter_shutter, "open",
    120     )
--> 121     yield from axis.tune(md=md)
    122     yield from bps.mv(
    123         ti_filter_shutter, "close",

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py in tune(self, md, **kwargs)
    981                 yield from self.pre_tune_method()
    982
--> 983             yield from self.tuner.tune(md=md, **kwargs)
    984
    985             if self.post_tune_method is not None:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/plans.py in tune(self, width, num, md)
    632             results.report()
    633
--> 634         return (yield from _scan(md=_md))
    635
    636

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/utils.py in dec_inner(*inner_args, **inner_kwargs)
   1009                 plan = gen_func(*inner_args, **inner_kwargs)
   1010                 plan = wrapper(plan, *args, **kwargs)
-> 1011                 return (yield from plan)
   1012             return dec_inner
   1013         return dec

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in subs_wrapper(plan, subs)
    380
    381     return (yield from finalize_wrapper(_inner_plan(),
--> 382                                         _unsubscribe()))
    383
    384

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in finalize_wrapper(plan, final_plan, pause_for                                                                         _debug)
    498     cleanup = True
    499     try:
--> 500         ret = yield from plan
    501     except GeneratorExit:
    502         cleanup = False

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in _inner_plan()
    377     def _inner_plan():
    378         yield from _subscribe()
--> 379         return (yield from plan)
    380
    381     return (yield from finalize_wrapper(_inner_plan(),

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/plans.py in _scan(md)
    623             if results.tune_ok.value:
    624                 yield from bps.create(name=stream_name)
--> 625                 yield from bps.read(results)
    626                 yield from bps.save()
    627

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/plan_stubs.py in read(obj)
     88         Msg('read', obj)
     89     """
---> 90     return (yield Msg('read', obj))
     91
     92

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1209                         # exceptions (coming in via throw) can be
   1210                         # raised
-> 1211                         new_response = yield from coro(msg)
   1212
   1213                     # special case `CancelledError` and let the outer

/share1/bluesky/conda_envs/bluesky/lib/python3.7/asyncio/coroutines.py in coro(*args, **kw)
    118         @functools.wraps(func)
    119         def coro(*args, **kw):
--> 120             res = func(*args, **kw)
    121             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    122                     isinstance(res, CoroWrapper)):

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _read(self, msg)
   1492             if obj not in self._describe_cache:
   1493                 # Validate that there is no data key name collision.
-> 1494                 data_keys = obj.describe()
   1495                 self._describe_cache[obj] = data_keys
   1496                 self._config_desc_cache[obj] = obj.describe_configuration()

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/ophyd/device.py in describe(self)
   1035             if component.kind & Kind.normal:
   1036                 component = getattr(self, component_name)
-> 1037                 res.update(component.describe())
   1038         return res
   1039

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/ophyd/signal.py in describe(self)
    216         val = self.value
    217         return {self.name: {'source': 'SIM:{}'.format(self.name),
--> 218                             'dtype': data_type(val),
    219                             'shape': data_shape(val)}}
    220

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/ophyd/utils/epics_pvs.py in data_type(val)
    311     raise ValueError(
    312         '{!r} '.format(val) +
--> 313         'not a valid type (int, float, ndarray, str, list, tuple)')
    314
    315

ValueError: None not a valid type (int, float, ndarray, str, list, tuple)
```

</p>
</details>

**Comment by prjemian** [comment]
Plot of data received.  Problem was that tuning identified this as actionable, even though a None was returned from the results.read().

![Clipboard01](https://user-images.githubusercontent.com/2279984/57654027-dde8a180-7598-11e9-87f7-418f46142023.jpg)

**Comment by prjemian** [comment]
This should go into apstools as an unusual case.  Test for non-zero values.

**Comment by prjemian** [comment]
nothing more to do here but wait for a fix from https://github.com/BCDA-APS/apstools/issues/139
