### ISSUE TITLE
Flyscan Wrong number of points reported 

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#264]
We receive this message:

```
New stream: 'aps_current_monitor'
HDF5 config: /share1/AreaDetectorConfig/FlyScan_config/saveFlyData.xml
HDF5 output: /share1/USAXS_data/2019-06/06_19_MPPlancheBS_3_usaxs/MP_TIN_5_0083.h5
flying, s    ar, deg      ay, mm       dy, mm       channel      elapsed, s 
5.01         11.0249010   -0.34679     12.52485     0            0.00       
10.02        11.0224350   -0.35626     12.48556     62           4.78       
15.03        11.0212391   -0.36043     12.46827     106          9.78       
20.04        11.0195785   -0.36698     12.44105     169          14.80      
25.04        11.0147792   -0.38534     12.36486     322          19.80      
30.05        11.0046456   -0.42487     12.20132     578          24.82      
35.05        10.9869260   -0.48943     11.93389     919          29.80      
40.06        10.9597542   -0.59560     11.49369     1341         34.82      
45.06        10.9192367   -0.74463     10.88547     1810         39.82      
50.07        10.8646712   -0.95308     10.00599     2326         44.83      
55.07        10.7913504   -1.22928     8.85650      2873         49.82      
60.07        10.6889085   -1.60835     7.29356      3475         54.83      
Exception in thread Thread-26686:
Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/threading.py", line 917, in _bootstrap_inner
    self.run()
  File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/32-usaxs_flyscan.py", line 78, in progress_reporting
    msg = _report_(t - self.t0)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/32-usaxs_flyscan.py", line 60, in _report_
    values.append(f"{channel}")
UnboundLocalError: local variable 'channel' referenced before assignment

writing fly scan HDF5 file: /share1/USAXS_data/2019-06/06_19_MPPlancheBS_3_usaxs/MP_TIN_5_0083.h5
finished writing fly scan HDF5 file: /share1/USAXS_data/2019-06/06_19_MPPlancheBS_3_usaxs/MP_TIN_5_0083.h5
HDF5 output complete: /share1/USAXS_data/2019-06/06_19_MPPlancheBS_3_usaxs/MP_TIN_5_0083.h5
New stream: 'mca'                                                                                                                                          
End-of-run baseline readings:
+--------------------------------+--------------------------------+
|                 guard_slit_bot | -0.4999999999999991            |
|                 guard_slit_inb | -0.5311999999999983            |
```

**Comment by prjemian** [comment]
Slightly different problem.  The *thread* that reports fly scan progress ended here with an exception that is fixed in changeset 0c37c59fdc8604c3fa11abf9b16ad7e29ac9f883.

Actual number of fly scan points is not affected.
