### ISSUE TITLE
RuntimeError: FAILED TO FIND CORRECT GAIN IN 9 AUTOSCALE ITERATIONS

### ISSUE THREAD

**Issue by jilavsky** [APS-USAXS/ipython-usaxs#270]
Tried to run data collection, this error came up:

```
final position: 8.8855708
tuning axis:  a_stage_r2p                                                                                                                                  
converged=[True, False, True, True, True, True]                                                                                                            
[E 08:10:27.107 run_engine:1261] Run aborted
    Traceback (most recent call last):
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1150, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1149, in baseline_wrapper
        return (yield from plan_mutator(plan, insert_baseline))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 378, in run_command_file
        yield from execute_command_list(filename, commands)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 425, in execute_command_list
        yield from before_command_list(md=md, commands=commands)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 106, in before_command_list
        yield from preUSAXStune(md=md)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 543, in preUSAXStune
        yield from tune(md=md)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py", line 375, in tune_a2rp
        yield from _tune_base_(a_stage.r2p, md=md)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py", line 135, in _tune_base_
        yield from autoscale_amplifiers([upd_controls, I0_controls, I00_controls])
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/22-amplifiers.py", line 502, in autoscale_amplifiers
        max_iterations=max_iterations)
      File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/22-amplifiers.py", line 478, in _scaler_autoscale_
        raise RuntimeError(msg)
    RuntimeError: FAILED TO FIND CORRECT GAIN IN 9 AUTOSCALE ITERATIONS
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-3-07ecb13f554f> in <module>
----> 1 RE(run_command_file('usaxs.mac'))

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    751                     # it (unless it is a canceled error)
    752                     if exc is not None:
--> 753                         raise exc
    754 
    755             if self._interrupted:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1260             self._reason = str(err)
   1261             self.log.exception("Run aborted")
-> 1262             raise err
   1263         finally:
   1264             # Some done_callbacks may still be alive in other threads.

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1148                     else:
   1149                         try:
-> 1150                             msg = self._plan_stack[-1].send(resp)
   1151                         # We have exhausted the top generator
   1152                         except StopIteration:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1147         return (yield from plan)
   1148     else:
-> 1149         return (yield from plan_mutator(plan, insert_baseline))
   1150 
   1151 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791 
    792 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849 
    850 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py in run_command_file(filename, md)
    376     """
    377     commands = get_command_list(filename)
--> 378     yield from execute_command_list(filename, commands)
    379 
    380 

/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py in execute_command_list(filename, commands, md)
    423     archive = instrument_archive(text)
    424 
--> 425     yield from before_command_list(md=md, commands=commands)
    426     for command in commands:
    427         action, args, i, raw_command = command

/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py in before_command_list(md, commands)
    104     if terms.preUSAXStune.run_tune_on_qdo.value:
    105         logger.info("Runing preUSAXStune as requested at start of measurements")
--> 106         yield from preUSAXStune(md=md)
    107 
    108     if constants["SYNC_ORDER_NUMBERS"]:

/home/beams11/USAXS/.ipython/profile_bluesky/startup/50-plans.py in preUSAXStune(md)
    541     for axis, tune in tuners.items():
    542         yield from bps.mv(ti_filter_shutter, "open")
--> 543         yield from tune(md=md)
    544         if axis.tuner.tune_ok:
    545             # If we don't wait, the next tune often fails

/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py in tune_a2rp(md)
    373     yield from bps.mv(upd_controls.auto.mode, "manual")
    374     md['plan_name'] = "tune_a2rp"
--> 375     yield from _tune_base_(a_stage.r2p, md=md)
    376     yield from bps.mv(upd_controls.auto.mode, "auto+background")
    377     yield from bps.sleep(0.1)   # piezo is fast, give the system time to react

/home/beams11/USAXS/.ipython/profile_bluesky/startup/29-axis_tuning.py in _tune_base_(axis, md)
    133         ti_filter_shutter, "open",
    134     )
--> 135     yield from autoscale_amplifiers([upd_controls, I0_controls, I00_controls])
    136     yield from axis.tune(md=md)
    137     yield from bps.mv(

/home/beams11/USAXS/.ipython/profile_bluesky/startup/22-amplifiers.py in autoscale_amplifiers(controls, shutter, count_time, max_iterations)
    500                 control_list,
    501                 count_time=count_time,
--> 502                 max_iterations=max_iterations)
    503 
    504 

/home/beams11/USAXS/.ipython/profile_bluesky/startup/22-amplifiers.py in _scaler_autoscale_(controls, count_time, max_iterations)
    476         msg = f"FAILED TO FIND CORRECT GAIN IN {max_iterations} AUTOSCALE ITERATIONS"
    477         if RE.state != "idle":      # don't raise if in summarize_plan()
--> 478             raise RuntimeError(msg)
    479 
    480 

RuntimeError: FAILED TO FIND CORRECT GAIN IN 9 AUTOSCALE ITERATIONS


```

**Comment by jilavsky** [comment]
This was in preUSAXstune, after ar tune and before a2rp tune. 
This is known issue which needs to be handles somehow - if amplifier is in overload state, it takes long time for it to recover from it. I believe spec simply gives up, but need to check the code.

**Comment by prjemian** [comment]
How long?

**Comment by jilavsky** [comment]
It happened again. I suspect this may need some sleep after opening the Ti shutter. May be the shutter is slow and so the code operates while shutter is opening. That would cause it to fail. 
In any case, if it fails it should still continue. Last thing we want is glitch to stop overnight runs. It may cause a bad data set, but if we have 12 hours of experiments, loss of single data set is not fatal - code must continue.
E.G.: I stepped out now and the thing stopped minute after I went for coffee. Lost time needlessly ;-)

**Comment by jilavsky** [comment]
Add may be 50 ms after opening?

**Comment by prjemian** [comment]
How long to wait?

**Comment by prjemian** [comment]
Let's try a combination of adding a bit of sleep (~50 ms) after opening the Ti shutter *and* not failing if it can't autoscale.  The latter will involve adding a custom exception that we can trap.

**Comment by prjemian** [comment]
I believe the correct place to add the wait is not after opening the shutter but just before running the scaler each iteration through the loop.  Just before the `trigger()` here before line 342: https://github.com/APS-USAXS/ipython-usaxs/blob/559aea84fc59c53d802f0016751ae2e5f9c55d3c/profile_bluesky/startup/22-amplifiers.py#L341-L343

**Comment by prjemian** [comment]
change 19d0ce2b7e342425cb167834107df1de7bc7c9f7 belongs here

**Comment by prjemian** [comment]
Could make the pre-trigger delay programmable rather than fixed.
