### ISSUE TITLE
need collection plan for linkam temperature controller support

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#292]
connect a linkam and create a BS plan to collect data during a ramp up-hold-down cycle

`t0 = time.time()`
1. collect RT USAXS/WAXS for N1
1. change temperature T
1. collect USAXS/WAXS while heating
1. when T reached, hold for N2 minutes, collecting data repeatedly
1. change T to RT
1. collect data while ramping
1. reach RT
1. collect final data

for collection, use name of: `f"{sample}_{temperature_C:.0f}C_{(time.time()-t0)/60:.0f}min"`

**Comment by prjemian** [comment]
From the documentation:

```
In [13]: linkam_ci94?                                                                                                                                         
Type:        Linkam_CI94
String form: Linkam_CI94(prefix='9idcLAX:ci94:', name='ci94', read_attrs=['signal'], configuration_attrs=[])
Docstring:  
Linkam model CI94 temperature controller

EXAMPLE::

    In [1]: linkam_ci94 = Linkam_CI94("9idcLAX:ci94:", name="ci94")

    In [2]: linkam_ci94.settled                                                                                                                                         
    Out[2]: False

    In [3]: linkam_ci94.settled                                                                                                                                         
    Out[3]: True
    
    linkam_ci94.record_signal()
    yield from (linkam_ci94.set_target(50))
```

**Comment by prjemian** [comment]
We ran into a problem (#293).  That gets in the way of this work.  We'll put this off until later.

**Comment by prjemian** [comment]
We have an error, the first thing we try:

```
In [1]: RE(linkam_tc1.set_target(40))                                                                                                                         
I 2019-08-05 10:04:03.303 - Set Linkam T96 to 40.00C
[E 10:04:03.304 run_engine:1261] Run aborted
    Traceback (most recent call last):
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1150, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1149, in baseline_wrapper
        return (yield from plan_mutator(plan, insert_baseline))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/home/beams/USAXS/.ipython/profile_bluesky/startup/10-devices.py", line 700, in set_target
        timeout_fail=timeout_fail)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py", line 1425, in wait_until_settled
        if self.settled:
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py", line 1415, in settled
        return diff <= self.tolerance
    TypeError: '<=' not supported between instances of 'float' and 'Signal'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-1-1a13a99841f7> in <module>
----> 1 RE(linkam_tc1.set_target(40))

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    751                     # it (unless it is a canceled error)
    752                     if exc is not None:
--> 753                         raise exc
    754 
    755             if self._interrupted:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1260             self._reason = str(err)
   1261             self.log.exception("Run aborted")
-> 1262             raise err
   1263         finally:
   1264             # Some done_callbacks may still be alive in other threads.

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1148                     else:
   1149                         try:
-> 1150                             msg = self._plan_stack[-1].send(resp)
   1151                         # We have exhausted the top generator
   1152                         except StopIteration:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1147         return (yield from plan)
   1148     else:
-> 1149         return (yield from plan_mutator(plan, insert_baseline))
   1150 
   1151 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791 
    792 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849 
    850 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

~/.ipython/profile_bluesky/startup/10-devices.py in set_target(self, target, wait, timeout, timeout_fail)
    698             yield from self.wait_until_settled(
    699                 timeout=timeout,
--> 700                 timeout_fail=timeout_fail)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py in wait_until_settled(self, timeout, timeout_fail)
   1423         _st = DeviceStatus(self.signal)
   1424 
-> 1425         if self.settled:
   1426             # just in case signal already at target
   1427             _st._finished(success=True)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py in settled(self)
   1413         """Is signal close enough to target?"""
   1414         diff = abs(self.signal.get() - self.target.value)
-> 1415         return diff <= self.tolerance
   1416 
   1417     def wait_until_settled(self, timeout=None, timeout_fail=False):

TypeError: '<=' not supported between instances of 'float' and 'Signal'

```

**Comment by prjemian** [comment]
should be `self.tolerance.value`, apparently intolerant of that oversight
