### ISSUE TITLE
Error from Linkam T96 heater

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#293]
when I set target tempearature I got this error message:

```
/home/beams11/USAXS/.ipython/profile_bluesky/startup/10-devices.py in set_target(self, target, wait, timeout, timeout_fail)
    693         yield from bps.mv(self.heating, 1)
    694 
--> 695         msg = f"Set {self.controller_name} to {set_point:.2f}{self.units.value}"
    696         specwriter._cmt("event", msg)
    697         logger.info(msg)

NameError: name 'set_point' is not defined
```

**Comment by prjemian** [comment]
Now, a new error:

```
In [11]: RE(linkam_tc1.set_target(24))                                                                                                                        
/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py:482: RuntimeWarning: coroutine 'Event.wait' was never awaited
  self._groups.clear()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
I 2019-08-01 14:43:49.567 - Set Linkam T96 to 24.00C
[E 14:43:49.569 run_engine:1261] Run aborted
    Traceback (most recent call last):
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py", line 1150, in _run
        msg = self._plan_stack[-1].send(resp)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1149, in baseline_wrapper
        return (yield from plan_mutator(plan, insert_baseline))
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 169, in plan_mutator
        raise ex
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py", line 122, in plan_mutator
        msg = plan_stack[-1].send(ret)
      File "<ipython-input-9-362b806b2828>", line 59, in set_target
        timeout_fail=timeout_fail)
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py", line 1425, in wait_until_settled
        if self.settled:
      File "/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py", line 1415, in settled
        return diff <= self.tolerance
    TypeError: '<=' not supported between instances of 'float' and 'Signal'
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-11-1b55256b93f3> in <module>
----> 1 RE(linkam_tc1.set_target(24))

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    751                     # it (unless it is a canceled error)
    752                     if exc is not None:
--> 753                         raise exc
    754 
    755             if self._interrupted:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1260             self._reason = str(err)
   1261             self.log.exception("Run aborted")
-> 1262             raise err
   1263         finally:
   1264             # Some done_callbacks may still be alive in other threads.

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1148                     else:
   1149                         try:
-> 1150                             msg = self._plan_stack[-1].send(resp)
   1151                         # We have exhausted the top generator
   1152                         except StopIteration:

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1147         return (yield from plan)
   1148     else:
-> 1149         return (yield from plan_mutator(plan, insert_baseline))
   1150 
   1151 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791 
    792 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849 
    850 

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    167                     continue
    168                 else:
--> 169                     raise ex
    170         # if inserting / mutating, put new generator on the stack
    171         # and replace the current msg with the first element from the

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    120             ret = result_stack.pop()
    121             try:
--> 122                 msg = plan_stack[-1].send(ret)
    123             except StopIteration as e:
    124                 # discard the exhausted generator

<ipython-input-9-362b806b2828> in set_target(self, target, wait, timeout, timeout_fail)
     57             yield from self.wait_until_settled(
     58                 timeout=timeout,
---> 59                 timeout_fail=timeout_fail)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py in wait_until_settled(self, timeout, timeout_fail)
   1423         _st = DeviceStatus(self.signal)
   1424 
-> 1425         if self.settled:
   1426             # just in case signal already at target
   1427             _st._finished(success=True)

/share1/bluesky/conda_envs/bluesky/lib/python3.7/site-packages/apstools/devices.py in settled(self)
   1413         """Is signal close enough to target?"""
   1414         diff = abs(self.signal.get() - self.target.value)
-> 1415         return diff <= self.tolerance
   1416 
   1417     def wait_until_settled(self, timeout=None, timeout_fail=False):

TypeError: '<=' not supported between instances of 'float' and 'Signal'

```
