### ISSUE TITLE
Ti filter controls jammed

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#32]
```
In [6]: ti_filter_shutter.open()
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-51393e6a787a> in <module>()
----> 1 ti_filter_shutter.open()

/home/beams11/USAXS/.ipython/profile_bluesky/startup/10-devices.py in open(self)
     73     def open(self):
     74         """request shutter to open, interactive use"""
---> 75         return self.set(self.open_value)
     76 
     77     def close(self):

/home/beams11/USAXS/.ipython/profile_bluesky/startup/10-devices.py in set(self, value, **kwargs)
     94             msg = "value should be one of " + " | ".join(acceptables)
     95             msg += " : received " + str(value)
---> 96             raise ValueError(msg)
     97 
     98         status = DeviceStatus(self)

ValueError: value should be one of open | close : received 1
```

then

```
In [10]: usaxs_shutter.open_value = "open"

In [11]: usaxs_shutter.open()
Out[11]: DeviceStatus(device=usaxs_shutter, done=False, success=False)

Exception in thread Thread-429:
Traceback (most recent call last):
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/APSshare/anaconda3/BlueSky/lib/python3.6/threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/10-devices.py", line 109, in run_and_delay
    move_shutter()
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/10-devices.py", line 102, in move_shutter
    self.open()     # no need to yield inside a thread
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/10-devices.py", line 75, in open
    return self.set(self.open_value)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/10-devices.py", line 90, in set
    raise RuntimeError("shutter is operating")
RuntimeError: shutter is operating
```

**Comment by prjemian** [comment]
proper values to open & close are `Up` and `Down`

```
In [3]: !caget 9idb:BioEnc2B3.ZNAM
9idb:BioEnc2B3.ZNAM            Down

In [4]: !caget 9idb:BioEnc2B3.ONAM
9idb:BioEnc2B3.ONAM            Up
```

**Comment by prjemian** [comment]
Also note an infinite loop inside `set().move_shutter().open().set()` ...
