### ISSUE TITLE
LimitError: Value 140.0 outside of range: [-113.4, 118.0]

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#331]
@jilavsky emailed:

> I was using BS to run mail in samples. 
> 
> BS crashed. Error message is still available in the terminal I am using. You can stop by and look at it when you can.
> 
> I went back to spec. Need to get through the samples and let AJ use the instrument.

**Comment by prjemian** [comment]
from the logs, you had finished

```
|2020-02-13 12:17:25.666|INFO|55969|main|50-plans|439|MainThread| - Command file: usaxs.mac
====== ======================= =============================
line # action                  parameters
====== ======================= =============================
2      CURRENT_EXPERIMENT_NAME GregStatic
21     saxsExp                 20, 0, 1, LeahTapeBlank
23     saxsExp                 20.000, 20.000, 1, LeahSample
25     saxsExp                 40, 40, 1, AirBlank
27     saxsExp                 20, 60, 0.82, Greg_7A
29     saxsExp                 20, 100, 0.75, Greg_7B
```


and these were the last lines logged:

```
|2020-02-13 12:22:07.820|DEBUG|55969|main|43-procedures|567|MainThread| - areaDetectorAcquire(): OrderedDict([('enable', 1), ('auto_increment', 'Yes'), ('array_counter', 0), ('auto_save', 'Yes'), ('num_capture', 0), ('file_template', '%s%s_%4.4d.hdf'), ('file_write_mode', 'Single'), ('blocking_callbacks', 'No'), ('parent.cam.array_callbacks', 1)])
|2020-02-13 12:22:12.841|INFO|55969|main|43-procedures|551|Thread-14324| - SAXS: 25.0s remaining
|2020-02-13 12:22:17.850|INFO|55969|main|43-procedures|551|Thread-14324| - SAXS: 20.0s remaining
|2020-02-13 12:22:22.862|INFO|55969|main|43-procedures|551|Thread-14324| - SAXS: 15.0s remaining
|2020-02-13 12:22:27.824|INFO|55969|main|43-procedures|551|Thread-14324| - SAXS: 10.0s remaining
|2020-02-13 12:22:32.835|INFO|55969|main|43-procedures|551|Thread-14324| - SAXS: 5.0s remaining
|2020-02-13 12:22:38.750|INFO|55969|main|43-procedures|580|MainThread| - Finished SAXS/WAXS data collection in 30.931344747543335 seconds.
|2020-02-13 12:22:38.778|INFO|55969|main|50-plans|1053|MainThread| - I0 value: 4445551.0
|2020-02-13 12:22:38.781|INFO|55969|main|50-plans|445|MainThread| - file line 31:           saxsExp     20     140    0.72    "Greg_8A"
|2020-02-13 12:22:38.791|INFO|55969|main|43-procedures|183|MainThread| - Prepared for SAXS mode
```

Too bad the logging did not capture the error.

**Comment by prjemian** [comment]
I did not remove the crash from terminal. Here it is (not colored, that did not pass through).

Seems like limit error, but I do not believe I changed any limits. 

<details>
<p>

```
I Thu-12:22:38 - Prepared for SAXS mode
[E 12:22:39.584 run_engine:1261] Run aborted                                                                                                
    Traceback (most recent call last):
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/run_engine.py", line 1127, in _run
        self._exception or resp)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1294, in __call__
        return (yield from plan)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 1149, in baseline_wrapper
        return (yield from plan_mutator(plan, insert_baseline))
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 790, in monitor_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 848, in fly_during_wrapper
        return (yield from plan2)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 77, in plan_mutator
        msg = plan_stack[-1].throw(exception)
      File "/home/beams/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 395, in run_command_file
        yield from execute_command_list(filename, commands)
      File "/home/beams/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 476, in execute_command_list
        yield from SAXS(sx, sy, sth, snm, md=_md)
      File "/home/beams/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 927, in SAXS
        s_stage.y, pos_Y,
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/plan_stubs.py", line 245, in mv
        ret = yield Msg('set', obj, val, group=group)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py", line 194, in plan_mutator
        inner_ret = yield msg
      [Previous line repeated 2 more times]
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/run_engine.py", line 1208, in _run
        new_response = yield from coro(msg)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/asyncio/coroutines.py", line 120, in coro
        res = func(*args, **kw)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/run_engine.py", line 1955, in _set
        ret = msg.obj.set(*msg.args, **kwargs)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/positioner.py", line 88, in set
        timeout=timeout)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/utils/epics_pvs.py", line 198, in wrapper
        return fcn(self, *args, **kwargs)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/epics_motor.py", line 149, in move
        status = super().move(position, **kwargs)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/positioner.py", line 183, in move
        self.check_value(position)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/epics_motor.py", line 216, in check_value
        self.user_setpoint.check_value(pos)
      File "/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/signal.py", line 1280, in check_value
        .format(value, low_limit, high_limit))
    ophyd.utils.errors.LimitError: Value 140.0 outside of range: [-113.4, 118.0]
---------------------------------------------------------------------------
LimitError                                Traceback (most recent call last)
<ipython-input-9-04b994fdd9b0> in <module>
----> 1 RE(run_command_file("usaxs.mac"))

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    751                     # it (unless it is a canceled error)
    752                     if exc is not None:
--> 753                         raise exc
    754
    755             if self._interrupted:

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1260             self._reason = str(err)
   1261             self.log.exception("Run aborted")
-> 1262             raise err
   1263         finally:
   1264             # Some done_callbacks may still be alive in other threads.

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1125                         try:
   1126                             msg = self._plan_stack[-1].throw(
-> 1127                                 self._exception or resp)
   1128                         except Exception as e:
   1129                             # The current plan did not handle it,

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in __call__(self, plan)
   1292         plan = monitor_during_wrapper(plan, self.monitors)
   1293         plan = baseline_wrapper(plan, self.baseline)
-> 1294         return (yield from plan)

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in baseline_wrapper(plan, devices, name)
   1147         return (yield from plan)
   1148     else:
-> 1149         return (yield from plan_mutator(plan, insert_baseline))
   1150
   1151

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in monitor_during_wrapper(plan, signals)
    788     plan1 = plan_mutator(plan, insert_after_open)
    789     plan2 = plan_mutator(plan1, insert_before_close)
--> 790     return (yield from plan2)
    791
    792

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in fly_during_wrapper(plan, flyers)
    846     plan1 = plan_mutator(plan, insert_after_open)
    847     plan2 = plan_mutator(plan1, insert_before_close)
--> 848     return (yield from plan2)
    849
    850

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
     75             # if we have a stashed exception, pass it along
     76             try:
---> 77                 msg = plan_stack[-1].throw(exception)
     78             except StopIteration as e:
     79                 # discard the exhausted generator

 
~/.ipython/profile_bluesky/startup/50-plans.py in run_command_file(filename, md)
    393     """
    394     commands = get_command_list(filename)
--> 395     yield from execute_command_list(filename, commands)
    396
    397

 
~/.ipython/profile_bluesky/startup/50-plans.py in execute_command_list(filename, commands, md)
    474             snm = args[3]
    475             _md.update(dict(sx=sx, sy=sy, thickness=sth, title=snm))
--> 476             yield from SAXS(sx, sy, sth, snm, md=_md)
    477
    478         elif action in ("waxs", "waxsexp"):

 
~/.ipython/profile_bluesky/startup/50-plans.py in SAXS(pos_X, pos_Y, thickness, scan_title, md)
    925     yield from bps.mv(
    926         s_stage.x, pos_X,
--> 927         s_stage.y, pos_Y,
    928     )
    929

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/plan_stubs.py in mv(*args)
    243     step, = utils.merge_cycler(cyl)
    244     for obj, val in step.items():
--> 245         ret = yield Msg('set', obj, val, group=group)
    246         status_objects.append(ret)
    247     yield Msg('wait', None, group=group)

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/preprocessors.py in plan_mutator(plan, msg_proc)
    192         try:
    193             # yield out the 'current message' and collect the return
--> 194             inner_ret = yield msg
    195         except GeneratorExit:
    196             # special case GeneratorExit.  We must clean up all of our plans

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/run_engine.py in _run(self)
   1206                         # exceptions (coming in via throw) can be
   1207                         # raised
-> 1208                         new_response = yield from coro(msg)
   1209
   1210                     # special case `CancelledError` and let the outer

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/asyncio/coroutines.py in coro(*args, **kw)
    118         @functools.wraps(func)
    119         def coro(*args, **kw):
--> 120             res = func(*args, **kw)
    121             if (base_futures.isfuture(res) or inspect.isgenerator(res) or
    122                     isinstance(res, CoroWrapper)):

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/bluesky/run_engine.py in _set(self, msg)
   1953         group = kwargs.pop('group', None)
   1954         self._movable_objs_touched.add(msg.obj)
-> 1955         ret = msg.obj.set(*msg.args, **kwargs)
   1956         p_event = asyncio.Event(loop=self.loop)
   1957         pardon_failures = self._pardon_failures

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/positioner.py in set(self, new_position, timeout, moved_cb, wait)
     86         """
     87         return self.move(new_position, wait=wait, moved_cb=moved_cb,
---> 88                          timeout=timeout)
     89
     90     def stop(self, *, success: bool =False):

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/utils/epics_pvs.py in wrapper(self, *args, **kwargs)
    196     def wrapper(self, *args, **kwargs):
    197         if self.connected:
--> 198             return fcn(self, *args, **kwargs)
    199         else:
    200             raise DisconnectedError('{} is not connected'.format(self.name))

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/epics_motor.py in move(self, position, wait, **kwargs)
    147         self._started_moving = False
    148
--> 149         status = super().move(position, **kwargs)
    150         self.user_setpoint.put(position, wait=False)
    151         try:

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/positioner.py in move(self, position, moved_cb, timeout)
    181             timeout = self._timeout
    182
--> 183         self.check_value(position)
    184
    185         self._run_subs(sub_type=self._SUB_REQ_DONE, success=False)

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/epics_motor.py in check_value(self, pos)
    214     def check_value(self, pos):
    215         '''Check that the position is within the soft limits'''
--> 216         self.user_setpoint.check_value(pos)
    217
    218     @required_for_connection

 
/share1/bluesky/conda_envs/bluesky_2020_1/lib/python3.7/site-packages/ophyd/signal.py in check_value(self, value)
   1278         if not (low_limit <= value <= high_limit):
   1279             raise LimitError('Value {} outside of range: [{}, {}]'
-> 1280                              .format(value, low_limit, high_limit))
   1281
   1282     def get_setpoint(self, *, as_string=None,

 
LimitError: Value 140.0 outside of range: [-113.4, 118.0]

 
In [10]:                          

```

</p>
</details>

**Comment by prjemian** [comment]
Yes, that is a `LimitError`.  Somehow, the motor motion (140) was outside the limits  *known to ophyd at the time* [-113.4, 118.0]:

```
LimitError: Value 140.0 outside of range: [-113.4, 118.0]
```

This was motor *SY*, right?

```
      File "/home/beams/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 476, in execute_command_list
        yield from SAXS(sx, sy, sth, snm, md=_md)
      File "/home/beams/USAXS/.ipython/profile_bluesky/startup/50-plans.py", line 927, in SAXS
        s_stage.y, pos_Y,
```

**Comment by prjemian** [comment]
a bit of research:

```
In [5]: m1.low_limit??                                                                                                                      
Type:        property
String form: <property object at 0x7fc5f45a2cb0>
Source:     
# m1.low_limit.fget
@property
def low_limit(self):
    return self.limits[0]

In [6]: m1.limits?                                                                                                                          
Type:        property
String form: <property object at 0x7fc5f4553a10>
Docstring:   <no docstring>

In [7]: m1.limits??                                                                                                                         
Type:        property
String form: <property object at 0x7fc5f4553a10>
Source:     
# m1.limits.fget
@property
@raise_if_disconnected
def limits(self):
    return self.user_setpoint.limits

In [8]: m1.user_setpoint.limits??                                                                                                           
Type:        property
String form: <property object at 0x7fc5f4598890>
Source:     
# m1.user_setpoint.limits.fget
@property
def limits(self):
    '''The PV control limits (low, high), such that low <= value <= high'''
    # This overrides the base Signal limits
    return (self._metadata['lower_ctrl_limit'],
            self._metadata['upper_ctrl_limit'])
```

**Comment by prjemian** [comment]
Ophyd learns the limits of an EpicsMotor from the initial connection.  It is not obvious it is programmed now to update that afterwards.  We need that ability to become routine.  Here is the `EpicsSignalBase.limits` property code:  https://github.com/bluesky/ophyd/blob/4b19598dc62e63cdba3b769d07481f91e044bae5/ophyd/signal.py#L886-L891

**Comment by prjemian** [comment]
related to https://github.com/BCDA-APS/apstools/issues/275

**Comment by prjemian** [comment]
exploring the suspicion this is from PyEpics ...

**Comment by prjemian** [comment]
Have developed and tested (briefly) a fix for this in the apstools package.

**Comment by prjemian** [comment]
Now using as part of `UsaxsMotor` device.  Testing on `tcam` motor.  Works as expected.

```
In [1]: object_explorer(tcam)                                                                                           
==================== ====================== =================
name                 PV reference           value            
==================== ====================== =================
acceleration         9idcLAX:m58:c1:m6.ACCL 0.2              
direction_of_travel  9idcLAX:m58:c1:m6.TDIR 1                
high_limit_switch    9idcLAX:m58:c1:m6.HLS  0                
home_forward         9idcLAX:m58:c1:m6.HOMF 0                
home_reverse         9idcLAX:m58:c1:m6.HOMR 0                
low_limit_switch     9idcLAX:m58:c1:m6.LLS  0                
motor_done_move      9idcLAX:m58:c1:m6.DMOV 1                
motor_egu            9idcLAX:m58:c1:m6.EGU  mm               
motor_is_moving      9idcLAX:m58:c1:m6.MOVN 0                
motor_stop           9idcLAX:m58:c1:m6.STOP 0                
offset_freeze_switch 9idcLAX:m58:c1:m6.FOFF 0                
set_use_switch       9idcLAX:m58:c1:m6.SET  0                
soft_limit_hi        9idcLAX:m58:c1:m6.HLM  39.53999999999999
soft_limit_lo        9idcLAX:m58:c1:m6.LLM  -70.36           
user_offset          9idcLAX:m58:c1:m6.OFF  -52.155          
user_offset_dir      9idcLAX:m58:c1:m6.DIR  1                
user_readback        9idcLAX:m58:c1:m6.RBV  -4.0             
user_setpoint        9idcLAX:m58:c1:m6.VAL  -4.0             
velocity             9idcLAX:m58:c1:m6.VELO 8.0              
==================== ====================== =================

Out[1]: <pyRestTable.rest_table.Table at 0x7f4b56a32c10>

In [2]: !caput 9idcLAX:m58:c1:m6.HLM 39.53                                                                              
Old : 9idcLAX:m58:c1:m6.HLM          39.54
New : 9idcLAX:m58:c1:m6.HLM          39.53

In [3]: object_explorer(tcam)                                                                                           
==================== ====================== =======
name                 PV reference           value  
==================== ====================== =======
acceleration         9idcLAX:m58:c1:m6.ACCL 0.2    
direction_of_travel  9idcLAX:m58:c1:m6.TDIR 1      
high_limit_switch    9idcLAX:m58:c1:m6.HLS  0      
home_forward         9idcLAX:m58:c1:m6.HOMF 0      
home_reverse         9idcLAX:m58:c1:m6.HOMR 0      
low_limit_switch     9idcLAX:m58:c1:m6.LLS  0      
motor_done_move      9idcLAX:m58:c1:m6.DMOV 1      
motor_egu            9idcLAX:m58:c1:m6.EGU  mm     
motor_is_moving      9idcLAX:m58:c1:m6.MOVN 0      
motor_stop           9idcLAX:m58:c1:m6.STOP 0      
offset_freeze_switch 9idcLAX:m58:c1:m6.FOFF 0      
set_use_switch       9idcLAX:m58:c1:m6.SET  0      
soft_limit_hi        9idcLAX:m58:c1:m6.HLM  39.53  
soft_limit_lo        9idcLAX:m58:c1:m6.LLM  -70.36 
user_offset          9idcLAX:m58:c1:m6.OFF  -52.155
user_offset_dir      9idcLAX:m58:c1:m6.DIR  1      
user_readback        9idcLAX:m58:c1:m6.RBV  -4.0   
user_setpoint        9idcLAX:m58:c1:m6.VAL  -4.0   
velocity             9idcLAX:m58:c1:m6.VELO 8.0    
==================== ====================== =======

Out[3]: <pyRestTable.rest_table.Table at 0x7f4b557174d0>

In [4]: !caput 9idcLAX:m58:c1:m6.HLM 39.54                                                                              
Old : 9idcLAX:m58:c1:m6.HLM          39.53
New : 9idcLAX:m58:c1:m6.HLM          39.54

In [5]: object_explorer(tcam)                                                                                           
==================== ====================== =======
name                 PV reference           value  
==================== ====================== =======
acceleration         9idcLAX:m58:c1:m6.ACCL 0.2    
direction_of_travel  9idcLAX:m58:c1:m6.TDIR 1      
high_limit_switch    9idcLAX:m58:c1:m6.HLS  0      
home_forward         9idcLAX:m58:c1:m6.HOMF 0      
home_reverse         9idcLAX:m58:c1:m6.HOMR 0      
low_limit_switch     9idcLAX:m58:c1:m6.LLS  0      
motor_done_move      9idcLAX:m58:c1:m6.DMOV 1      
motor_egu            9idcLAX:m58:c1:m6.EGU  mm     
motor_is_moving      9idcLAX:m58:c1:m6.MOVN 0      
motor_stop           9idcLAX:m58:c1:m6.STOP 0      
offset_freeze_switch 9idcLAX:m58:c1:m6.FOFF 0      
set_use_switch       9idcLAX:m58:c1:m6.SET  0      
soft_limit_hi        9idcLAX:m58:c1:m6.HLM  39.54  
soft_limit_lo        9idcLAX:m58:c1:m6.LLM  -70.36 
user_offset          9idcLAX:m58:c1:m6.OFF  -52.155
user_offset_dir      9idcLAX:m58:c1:m6.DIR  1      
user_readback        9idcLAX:m58:c1:m6.RBV  -4.0   
user_setpoint        9idcLAX:m58:c1:m6.VAL  -4.0   
velocity             9idcLAX:m58:c1:m6.VELO 8.0    
==================== ====================== =======

Out[5]: <pyRestTable.rest_table.Table at 0x7f4b5570f190>
```
