### ISSUE TITLE
FlyScan failed to save HDF5 data

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#347]
Got some error during the fly scan today.  Might be a temporary problem or a problem with a `-` in the title.

<details>

```
 Thu-11:58:59 - progress_reporting has arrived
Exception in thread Thread-3452:
Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/usaxs_fly_scan.py", line 145, in prepare_HDF5_file
    user_data.set_state_blocking("FlyScanning: " + os.path.split(fname)[-1])
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/user_data.py", line 49, in set_state_blocking
    self.state.put(msg)
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/site-packages/ophyd/signal.py", line 1632, in put
    timeout=timeout, **kwargs)
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/site-packages/ophyd/_pyepics_shim.py", line 82, in put
    callback_data=callback_data)
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/site-packages/epics/pv.py", line 55, in wrapped
    return func(self, *args, **kwargs)
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/site-packages/epics/pv.py", line 656, in put
    callback_data=callback_data)
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/site-packages/epics/ca.py", line 612, in wrapper
    return fcn(*args, **kwds)
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/site-packages/epics/ca.py", line 1718, in put
    PySEVCHK('put', ret)
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/site-packages/epics/ca.py", line 661, in PySEVCHK
    raise CASeverityException(func_name, message(status))
epics.ca.CASeverityException:  put returned 'Invalid string'

I Thu-11:59:00 - flying, s    ar, deg      ay, mm       dy, mm       channel      elapsed, s 
D Thu-11:59:04 - 5.00         8.7485658    0.00646      12.65112     0            0.00       
D Thu-11:59:09 - 10.01        8.7468858    -0.00006     12.62318     50           4.78       
D Thu-11:59:14 - 15.02        8.7446930    -0.00883     12.58453     127          9.78       
D Thu-11:59:19 - 20.03        8.7372125    -0.03834     12.45936     328          14.80      
D Thu-11:59:24 - 25.03        8.7230626    -0.09490     12.22185     625          19.80      
D Thu-11:59:29 - 30.04        8.7001047    -0.18214     11.84779     992          24.80      
D Thu-11:59:34 - 35.04        8.6680997    -0.30772     11.33014     1408         29.80      
D Thu-11:59:39 - 40.04        8.6248561    -0.47163     10.6222



I Thu-12:00:38 - finished writing fly scan HDF5 file: /share1/USAXS_data/2020-06/06_18_testAutoCollect_usaxs/GlassyCarbonM5_Step_0936.h5
Exception in thread Thread-3463:
Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/usaxs_fly_scan.py", line 158, in finish_HDF5_file
    raise RuntimeError("Must first call prepare_HDF5_file()")
RuntimeError: Must first call prepare_HDF5_file()

I Thu-12:00:38 - 98.85        7.0993770    -6.27000     -13.98123    7999         93.57      
D Thu-12:00:38 - 98.8662109375s - progress_reporting is done
New stream: 'mca'                                                                                                                                                       
D Thu-12:00:38 - after return: 99.18004727363586s
                                                                                                                                                                        
  A 'deferred pause' has been requested. The RunEngine will pause at the next checkpoint. To pause immediately, hit Ctrl+C again in the next 10 seconds.                
Deferred pause acknowledged. Continuing to checkpoint.                                                                                                                  
^Ctrying a second timeng for next user command
Pausing...
---------------------------------------------------------------------------
RunEngineInterrupted                      Traceback (most recent call last)
<ipython-input-5-323950aec116> in <module>
----> 1 RE(auto_collect.remote_ops())

/share1/bluesky/conda_envs/bluesky_2020_5/lib/python3.7/site-packages/bluesky/run_engine.py in __call__(self, *args, **metadata_kw)
    798 
    799         if self._interrupted:
--> 800             raise RunEngineInterrupted(self.pause_msg) from None
    801 
    802         return tuple(self._run_start_uids)

RunEngineInterrupted: 
Your RunEngine is entering a paused state. These are your options for changing
the state of the RunEngine:

RE.resume()    Resume the plan.
RE.abort()     Perform cleanup, then kill plan. Mark exit_stats='aborted'.
RE.stop()      Perform cleanup, then kill plan. Mark exit_status='success'.
RE.halt()      Emergency Stop: Do not perform cleanup --- just stop.
```

</details>

**Comment by prjemian** [comment]
Trap this with `try..except`:

```
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/user_data.py", line 49, in set_state_blocking
    self.state.put(msg)
```

**Comment by prjemian** [comment]
Let's stop with that change for now.  There is `instrument.utils.cleanupText()` but this is not safe to use on full path file names since it will replace `/` with `_`.

Best to wait for this error to recur and see what the diagnostic prints (message text and exception text).
