### ISSUE TITLE
Can't call bluesky-config saveFlyData.py from SPEC

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#363]
@jilavsky emails this BUG report:

```
Traceback (most recent call last):a 9 sec
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 28, in <module>
    from . import nexus
ImportError: attempted relative import with no known parent package
```

**Comment by prjemian** [comment]
Sorry, missed that situation.  Need to have this directory (`/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/`) on the PYTHONPATH for this to work.  Even then, it might take some more handling.

For now, revert SPEC to previous `saveFlyData.py` code (toggle the commented lines in the `usaxs_flyscan.mac` file).

**Comment by prjemian** [comment]
@jilavsky emails an update

> That has some other complain:
> 
> ```
> Tue Jul 28 11:22:38 2020.  Please wait approximately 105s to complete FlyScan..
> Traceback (most recent call last):
>   File "_ctypes/callbacks.c", line 315, in 'calling callback function'
>   File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/epics/ca.py", line 512, in _onMonitorEvent
>     args.usr(value=value, **kwds)
> TypeError: __on_connect() got an unexpected keyword argument 'count'
> ```
> But data look good.

**Comment by prjemian** [comment]
The old code should be run with EPD, not Anaconda.  There _must_ be more lines to toggle the comments.

**Comment by prjemian** [comment]
Aha!, Those lines in use now read:

```
  # old Python 2.7 code using Enthought Python Distribution
   _PYTHON = "/APSshare/anaconda/x86_64/bin/python"
   _saveFlyData = "/home/beams/USAXS/Documents/eclipse/USAXS/tools/saveFlyData.py"
   _saveFlyData_XML = "/home/beams/USAXS/Documents/eclipse/USAXS/tools/saveFlyData.xml"
```

**Comment by prjemian** [comment]
Why not:

    _PYTHON = "/APSshare/epd/rh6-x86_64/bin/python"

Check the SVN history to see if/when that was changed to anaconda.

**Comment by prjemian** [comment]
Or, I fix the original problem and we move on.

**Comment by prjemian** [comment]
Anyway, here's is what subversion tells us:

```
-  _EPD = "/APSshare/anaconda/x86_64/bin/python"
-  _EPDsaveFlyData = "/home/beams/USAXS/Documents/eclipse/USAXS/tools/saveFlyData.py"
-  _EPDcfgFlyData = "/home/beams/USAXS/Documents/eclipse/USAXS/tools/saveFlyData.xml"
+  #
+  # old Python 2.7 code using Enthought Python Distribution
+   _PYTHON = "/APSshare/anaconda/x86_64/bin/python"
+   _saveFlyData = "/home/beams/USAXS/Documents/eclipse/USAXS/tools/saveFlyData.py"
+   _saveFlyData_XML = "/home/beams/USAXS/Documents/eclipse/USAXS/tools/saveFlyData.xml"
+  #
+  # 2020-07-24, PRJ:
+  # new Python 3.7 code using Bluesky and Anaconda Python
+  # _PYTHON = "/APSshare/anaconda3/Bluesky/bin/python"
+  # _saveFlyData = "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py"
+  # _saveFlyData_XML = "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.xml"
+  #
```

Summary: 

* The old code had been migrated to use Anaconda.
* The comment about using EPD is stale.
* Change the startup for the new code.

**Comment by prjemian** [comment]
Can start the new code as a Python module with its directory in the path.

**Comment by prjemian** [comment]
A `try..except` clause should fix the original problem:

```
try:
    # when used as a package
    from . import nexus
except ImportError:
    # when run standalone
    import nexus
```

**Comment by prjemian** [comment]
Ready to revert `~/spec/macros/local/usaxs_flyscan.mac` to the bluesky code now.
