### ISSUE TITLE
flyscan not saving data from Bluesky (or SPEC)

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#394]
Probably two different problems.  In Bluesky, the PV did not connect.  What's up?

```
D Mon-16:06:26 - make_filename: /mnt/share1/USAXS_data/2020-09/09_14_setup/09_14_setup_usaxs/Blank_0030.jpg
Transient Scan ID: 97     Time: 2020-09-14 16:06:27/2020-09/09_14_setup/09_14_setup_usaxs/
Persistent Unique Scan ID: '95ed63da-405b-4ef0-b803-7a4099a98f63'
New stream: 'baseline'
New stream: 'aps_current_monitor'
I Mon-16:06:27 - HDF5 config: /share1/AreaDetectorConfig/FlyScan_config/saveFlyData.xml
I Mon-16:06:27 - HDF5 output: /share1/USAXS_data/2020-09/09_14_setup/09_14_setup_usaxs/Blank_0029.h5
D Mon-16:06:27 - progress_reporting has arrived
I Mon-16:06:28 - flying, s    ar, deg      ay, mm       dy, mm       channel      elapsed, s 
D Mon-16:06:32 - 5.01         8.7495084    0.00634      12.62800     0            0.00       
D Mon-16:06:37 - 10.01        8.7495084    0.00634      12.62800     0            0.00       
D Mon-16:06:42 - 15.02        8.7495084    0.00634      12.62800     0            0.00       
Exception in thread Thread-1681:
Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/usaxs_fly_scan.py", line 149, in prepare_HDF5_file
    self.saveFlyData = SaveFlyScan(
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 61, in __init__
    self._prepare_to_acquire()
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 190, in _prepare_to_acquire
    raise EpicsNotConnected()
usaxs_support.saveFlyData.EpicsNotConnected


D Mon-16:08:37 - 130.12       7.7959089    -3.35198     -2.13450     6094         74.95      
D Mon-16:08:42 - 135.12       7.6174882    -3.97171     -4.83676     6658         79.95      
D Mon-16:08:47 - 140.13       7.4258198    -4.65804     -7.85190     7229         84.97      
D Mon-16:08:52 - 145.14       7.2129260    -5.38757     -11.12228    7801         89.97      
D Mon-16:08:56 - writing fly scan HDF5 file: /share1/USAXS_data/2020-09/09_14_setup/09_14_setup_usaxs/Blank_0029.h5
Exception in thread Thread-1692:
Traceback (most recent call last):
I Mon-16:08:56 - finished writing fly scan HDF5 file: /share1/USAXS_data/2020-09/09_14_setup/09_14_setup_usaxs/Blank_0029.h5
  File "/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/threading.py", line 932, in _bootstrap_inner
I Mon-16:08:56 - 148.81       7.1002340    -5.75230     -12.65241    7999         93.60      
    self.run()
  File "/share1/bluesky/conda_envs/bluesky_2020_9/lib/python3.8/threading.py", line 870, in run
D Mon-16:08:56 - 148.81736397743225s - progress_reporting is done
    self._target(*self._args, **self._kwargs)
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/usaxs_fly_scan.py", line 159, in finish_HDF5_file
    raise RuntimeError("Must first call prepare_HDF5_file()")
RuntimeError: Must first call prepare_HDF5_file()
New stream: 'mca'                                                                                                                                                             
D Mon-16:08:56 - after return: 149.12686467170715s
Out[6]:                                                                                                                                                                       
('4f562df1-1b30-4d5c-803b-2f61b5a7d216',                                                                                                                                      
 'ccc8aac1-41b4-4317-9a48-8ba6d305b57d',                                                                                                                                      
 '7185fdd3-78ea-4e3f-9398-bb8919c81355',
 'ed715c9e-e931-4a46-85cf-5cc405289cd2',
 '95ed63da-405b-4ef0-b803-7a4099a98f63')

In [7]: 
```

**Comment by prjemian** [comment]
The Linkam controller must be turned on.

```
support/saveFlyData.py /home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_ 
None EpicsSignalDesc(read_pv='9idcLINKAM:tc1:temperature_RBV', name='metadata_0317', timestamp=1600118670.7087379, auto_monitor=False, string=False, write_pv='9idcLINKAM:tc1:temperature_RBV', limits=False, put_complete=False)
None EpicsSignalDesc(read_pv='9idcLINKAM:tc1:heating', name='metadata_0318', timestamp=1600118670.7104278, auto_monitor=False, string=False, write_pv='9idcLINKAM:tc1:heating', limits=False, put_complete=False)
None EpicsSignalDesc(read_pv='9idcLINKAM:tc1:rampRate_RBV', name='metadata_0319', timestamp=1600118670.713771, auto_monitor=False, string=False, write_pv='9idcLINKAM:tc1:rampRate_RBV', limits=False, put_complete=False)
None EpicsSignalDesc(read_pv='9idcLINKAM:tc1:rampLimit_RBV', name='metadata_0320', timestamp=1600118670.7157164, auto_monitor=False, string=False, write_pv='9idcLINKAM:tc1:rampLimit_RBV', limits=False, put_complete=False)
None EpicsSignalDesc(read_pv='9idcLINKAM:tc1:statusError_RBV', name='metadata_0321', timestamp=1600118670.7177289, auto_monitor=False, string=False, write_pv='9idcLINKAM:tc1:statusError_RBV', limits=False, put_complete=False)
None EpicsSignalDesc(read_pv='9idcLINKAM:tc1:lnpStatus_RBV', name='metadata_0322', timestamp=1600118670.7193604, auto_monitor=False, string=False, write_pv='9idcLINKAM:tc1:lnpStatus_RBV', limits=False, put_complete=False)
None EpicsSignalDesc(read_pv='9idcLINKAM:tc1:vacuumLimit_RBV', name='metadata_0323', timestamp=1600118670.721394, auto_monitor=False, string=False, write_pv='9idcLINKAM:tc1:vacuumLimit_RBV', limits=False, put_complete=False)
None EpicsSignalDesc(read_pv='9idcLINKAM:tc1:vacuumStatus_RBV', name='metadata_0324', timestamp=1600118670.72253, auto_monitor=False, string=False, write_pv='9idcLINKAM:tc1:vacuumStatus_RBV', limits=False, put_complete=False)
```

**Comment by prjemian** [comment]
# SPEC

In SPEC, the problem is different.  SPEC sees this:

```
Mon Sep 14 16:36:10 2020.  Please wait approximately 105s to complete FlyScan..
Traceback (most recent call last):a 6 sec
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 30, in <module>
    from . import nexus
ImportError: attempted relative import with no known parent package
```

**Comment by prjemian** [comment]
But we have handling in place for that: https://github.com/APS-USAXS/ipython-usaxs/blob/b5af68c69cd59813d15ed67b51a098b82028a88b/profile_bluesky/startup/usaxs_support/saveFlyData.py#L28-L33

**Comment by prjemian** [comment]
hint: https://stackoverflow.com/questions/3131217/error-handling-when-importing-modules

**Comment by prjemian** [comment]
or https://stackoverflow.com/questions/20226347/importing-python-libraries-and-gracefully-handling-if-they-are-not-availalble/20228312#20228312

**Comment by prjemian** [comment]
https://docs.python.org/3/library/importlib.html#importlib.import_module

like this, maybe:

```
try:
    lib = import_module("nexus", package=".")
# except ImportError:
except Exception as exc:
    logger.info("fallback import handling due to %s", exc)
    import nexus    # when run standalone
else:
    globals()["nexus"] = lib
```

**Comment by prjemian** [comment]
next problem in SPEC:

```

Mon Sep 14 16:57:08 2020.  Please wait approximately 105s to complete FlyScan..
Traceback (most recent call last):a 6 sec
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 376, in initialize_libca
    libca = load_dll(find_libca())
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libca.so.3.14: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 376, in initialize_libca
    libca = load_dll(find_libca())
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libca.so.3.14: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 30, in <module>
    lib = import_module("nexus", package=".")
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/usaxs_support/nexus.py", line 25, in <module>
    from ophyd import Component, EpicsSignal
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 71, in <module>
    set_cl()
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 21, in set_cl
    set_cl(c_type, pv_telemetry=pv_telemetry)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 40, in set_cl
    shim.setup(logger)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/_pyepics_shim.py", line 164, in setup
    context=ca.current_context(), logger=logger)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 546, in wrapper
    initialize_libca()
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 378, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: libca.so.3.14: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 376, in initialize_libca
    libca = load_dll(find_libca())
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libca.so.3.14: cannot open shared object file: No such file or directory
Traceback (most recent call last):
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 376, in initialize_libca
    libca = load_dll(find_libca())
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libca.so.3.14: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 30, in <module>
    lib = import_module("nexus", package=".")
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/usaxs_support/nexus.py", line 25, in <module>
    from ophyd import Component, EpicsSignal
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 71, in <module>
    set_cl()
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 21, in set_cl
    set_cl(c_type, pv_telemetry=pv_telemetry)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 40, in set_cl
    shim.setup(logger)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/_pyepics_shim.py", line 164, in setup
    context=ca.current_context(), logger=logger)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 546, in wrapper
    initialize_libca()
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 378, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: libca.so.3.14: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 376, in initialize_libca
    libca = load_dll(find_libca())
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 442, in LoadLibrary
    return self._dlltype(name)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libca.so.3.14: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/beams/USAXS/.ipython/profile_bluesky/startup/usaxs_support/saveFlyData.py", line 34, in <module>
    import nexus    # when run standalone
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/usaxs_support/nexus.py", line 25, in <module>
    from ophyd import Component, EpicsSignal
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 71, in <module>
    set_cl()
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 21, in set_cl
    set_cl(c_type, pv_telemetry=pv_telemetry)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/__init__.py", line 40, in set_cl
    shim.setup(logger)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/ophyd/_pyepics_shim.py", line 164, in setup
    context=ca.current_context(), logger=logger)
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 546, in wrapper
    initialize_libca()
  File "/APSshare/anaconda3/Bluesky/lib/python3.7/site-packages/epics/ca.py", line 378, in initialize_libca
    raise ChannelAccessException('loading Epics CA DLL failed: ' + str(exc))
epics.ca.ChannelAccessException: loading Epics CA DLL failed: libca.so.3.14: cannot open shared object file: No such file or directory
^Citing for Flyscan to collect data 10 sec

Mon Sep 14 16:57:19 2020.  Resetting Fly USAXS, hang on, this is complex procedure.

Mon Sep 14 16:57:21 2020.  Still waiting for FlyScan to abort.
Not a command or macro:  "FS_disableARSP".
Warning:  cleanup macro didn't complete.

50.USAXS> 
```

**Comment by prjemian** [comment]
http://pyepics.github.io/pyepics/installation.html?highlight=find_libca#getting-started-setting-up-the-epics-environment

**Comment by prjemian** [comment]
tested with SPEC - success
