### ISSUE TITLE
BUG: on startup, TimeoutError due to missing PV 9idcLAX:USAXS:updEnable

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#535]
```bash
usaxs@usaxscontrol /share1/USAXS_data $ blueskyUSAXS
Python 3.8.2 (default, Mar 26 2020, 15:53:00)
Type 'copyright', 'credits' or 'license' for more information
IPython 7.19.0 -- An enhanced Interactive Python. Type '?' for help.

IPython profile: bluesky
Exception reporting mode: Minimal
Activating auto-logging. Current session state plus future input saved.
Filename       : /share1/USAXS_data/.logs/ipython_console.log
Mode           : rotate
Output logging : True
Raw input log  : False
Timestamping   : True
State          : active
I Mon-12:02:43 - ############################################################ startup
I Mon-12:02:43 - logging started
I Mon-12:02:43 - logging level = 10
I Mon-12:02:43 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/collection.py
I Mon-12:02:43 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/mpl/console.py
I Mon-12:02:44 - bluesky framework
I Mon-12:02:44 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/framework/check_python.py
I Mon-12:02:44 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/framework/initialize.py
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/framework/user_dir.py
I Mon-12:02:46 - User code directory: /home/beams/USAXS/.ipython/user
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/framework/metadata.py
/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/intake/__init__.py:39: UserWarning: deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog
 If you want to open a generic URL, you should use intake.open_catalog
  warnings.warn('deprecation: intake.Catalog now references the base class intake.catalog.base.Catalog\n '
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/framework/callbacks.py
I Mon-12:02:46 - writing to SPEC file: /share1/USAXS_data/20220124-120246.dat
I Mon-12:02:46 -    >>>>   Using default SPEC file name   <<<<
I Mon-12:02:46 -    file will be created when bluesky ends its next scan
I Mon-12:02:46 -    to change SPEC file, use command:   newUser(user)
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/aps_source.py
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/permit.py
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/diagnostics.py
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/override_parameters.py
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/constants.py
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/general_terms.py
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/amplifiers.py
I Mon-12:02:46 - /home/beams/USAXS/.ipython/profile_bluesky/startup/instrument/devices/scalers.py
[TerminalIPythonApp] WARNING | Unknown error in handling startup files:
TimeoutError: 9idcLAX:USAXS:updEnable could not connect within 5.0-second timeout.

The above exception was the direct cause of the following exception:
ConnectionTimeoutError: Failed to connect to 9idcLAX:USAXS:updEnable within 5.00 sec


In [1]:
```

**Comment by jilavsky** [comment]
This looks like BS back end issue. There is no 9idcLAX:USAXS:updEnable PV in LAX and never was. There is 9idcLAX:USAXS:upd and this is called on line 635 of amplifiers.py as PV inside SwaitRecord. I have not found USAXS:upd used anywhere else in BS. 
Looks to me that BS assumes this POV has Enable and Disable fields associated with it, however creates incorrect PV name (missing "." before Enable). This 9idcLAX:USAXS:upd is created in USAXScalcs.db on LAX as grecord(swait, "9idcLAX:USAXS:upd"). It may have Enable/Disable PVs. 
Is this some kind of back end improvement on BS? There are few more similar SwaitRecords with 9idcLAX:USAXS:trd, 9idcLAX:USAXS:I0, 9idcLAX:USAXS:I00, and 9idcLAX:USAXS:I000. These are after the place where you have crash, but I suspect we will have same issue on those.

**Comment by prjemian** [comment]
More details (matching previous comment):

```python
In [1]: import traceback

In [2]: traceback.print_last()
Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 1116, in _get_with_timeout
    self.wait_for_connection(timeout=connection_timeout)
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 1495, in wait_for_connection
    self._ensure_connected(self._read_pv, self._write_pv, timeout=timeout)
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 1047, in _ensure_connected
    raise TimeoutError(f"{pv.pvname} could not connect within "
TimeoutError: 9idcLAX:USAXS:updEnable could not connect within 5.0-second timeout.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/IPython/core/shellapp.py", line 409, in _run_startup_files
    self._exec_file(fname)
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/IPython/core/shellapp.py", line 377, in _exec_file
    self.shell.safe_execfile(full_filename,
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/IPython/core/interactiveshell.py", line 2740, in safe_execfile
    py3compat.execfile(
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/IPython/utils/py3compat.py", line 168, in execfile
    exec(compiler(f.read(), fname, 'exec'), glob, loc)
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/00-instrument.py", line 17, in <module>
    from instrument.collection import *
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/collection.py", line 14, in <module>
    from .devices import *
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/__init__.py", line 10, in <module>
    from .general_terms import *
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/general_terms.py", line 17, in <module>
    from .amplifiers import upd_controls
  File "/home/beams11/USAXS/.ipython/profile_bluesky/startup/instrument/devices/amplifiers.py", line 637, in <module>
    upd_photocurrent = upd_photocurrent_calc.get()
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/device.py", line 1361, in get
    values[attr] = signal.get(**kwargs)
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 1180, in get
    info = self._get_with_timeout(
  File "/share1/bluesky/conda_envs/bluesky_2021_1/lib/python3.8/site-packages/ophyd/signal.py", line 1118, in _get_with_timeout
    raise ConnectionTimeoutError(
ophyd.signal.ConnectionTimeoutError: Failed to connect to 9idcLAX:USAXS:updEnable within 5.00 sec

```

**Comment by prjemian** [comment]
The connection with `{PV}Enable` PV comes from `apstools.synApps.SwaitRecord`.  Either that PV depends on the synApps version or comes from the `userCalc` database.  Either way, it could be a problem here.  We can fix it locally with a subclass for now.

**Comment by jilavsky** [comment]
Should it be {PV}.Enable ?

**Comment by prjemian** [comment]
Instances:

https://github.com/APS-USAXS/ipython-usaxs/blob/ab4c0fc89b656bac08196269a6f9d0b4d879b351/profile_bluesky/startup/instrument/devices/amplifiers.py#L634-L636

https://github.com/APS-USAXS/ipython-usaxs/blob/ab4c0fc89b656bac08196269a6f9d0b4d879b351/profile_bluesky/startup/instrument/devices/amplifiers.py#L649-L651

https://github.com/APS-USAXS/ipython-usaxs/blob/ab4c0fc89b656bac08196269a6f9d0b4d879b351/profile_bluesky/startup/instrument/devices/amplifiers.py#L664-L666

https://github.com/APS-USAXS/ipython-usaxs/blob/ab4c0fc89b656bac08196269a6f9d0b4d879b351/profile_bluesky/startup/instrument/devices/amplifiers.py#L679-L681
