### ISSUE TITLE
specplots.log error

### ISSUE THREAD

**Issue by prjemian** [APS-USAXS/ipython-usaxs#77]
every five minutes now, this error:

```
#= 28685 --Start--- Fri Nov  9 09:55:01 CST 2018
#= 28709 --faulthandler---------- module enabled
[specplotsAllScans.py 28709 2018-11-09 09:55:02.667728] faulthandler: module enabled
Traceback (most recent call last):
  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/specplotsAllScans.py", line 344, in <module>
    plotAllSpecFileScans(specFile)
  File "/home/beams/USAXS/Documents/eclipse/USAXS/livedata/specplotsAllScans.py", line 127, in plotAllSpecFileScans
    for scan_number in sd.getScanNumbers():
  File "/APSshare/anaconda/x86_64/lib/python2.7/site-packages/spec2nexus/spec.py", line 294, in getScanNumbers
    return sorted(self.scans.keys(), key=int)
ValueError: invalid literal for int() with base 10: '35.1'
#= 28685 --Done---------------------------------- Fri Nov  9 09:55:02 CST 2018
```

**Comment by prjemian** [comment]
same problem due to two #F sections in SPEC data file

**Comment by prjemian** [comment]
Exception *should* also report the file name (absolute, full path)

**Comment by prjemian** [comment]
duplicate of #76
